### ISSUE TITLE
Can't access "/catalog-import" path with custom "CatalogIndexPage"

### ISSUE THREAD

**Issue by webark** [backstage/backstage#10533]
## Expected Behavior

when setting up a custom catalog index page navigating to the `catalog-import` path loads up the "catalog index" content

## Actual Behavior

Should load the "catalog-import" content

## Steps to Reproduce

1. Create a custom index page and configure the route as persribed like
```jsx
    <Route path="/catalog" element={<CatalogIndexPage />}>
      <CustomCatalogIndexPage />
    </Route>
```
2. Navigate to the `/catalog-import` path.

## Context

followed instructions here https://backstage.io/docs/features/software-catalog/catalog-customization

## Your Environment

- Browser Information: FIrefox 99.0b8

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.3.0 - darwin/x64
node: v17.6.0
yarn: 1.22.15
cli:  0.16.0 (installed)

Dependencies:
  @backstage/app-defaults                            1.0.0
  @backstage/backend-common                          0.13.1
  @backstage/backend-tasks                           0.2.1
  @backstage/catalog-client                          1.0.0
  @backstage/catalog-model                           1.0.0
  @backstage/cli-common                              0.1.8
  @backstage/cli                                     0.16.0
  @backstage/config-loader                           1.0.0
  @backstage/config                                  1.0.0
  @backstage/core-app-api                            1.0.0
  @backstage/core-components                         0.9.2
  @backstage/core-plugin-api                         1.0.0
  @backstage/dev-utils                               1.0.0
  @backstage/errors                                  1.0.0
  @backstage/integration-react                       1.0.0
  @backstage/integration                             1.0.0
  @backstage/plugin-api-docs                         0.8.3
  @backstage/plugin-app-backend                      0.3.30
  @backstage/plugin-auth-backend                     0.12.2
  @backstage/plugin-auth-node                        0.1.6
  @backstage/plugin-catalog-backend-module-bitbucket 0.1.1
  @backstage/plugin-catalog-backend                  1.0.0
  @backstage/plugin-catalog-common                   1.0.0
  @backstage/plugin-catalog-graph                    0.2.15
  @backstage/plugin-catalog-import                   0.8.6
  @backstage/plugin-catalog-react                    1.0.0
  @backstage/plugin-catalog                          1.0.0
  @backstage/plugin-github-actions                   0.5.3
  @backstage/plugin-org                              0.5.3
  @backstage/plugin-permission-backend               0.5.5
  @backstage/plugin-permission-common                0.5.3
  @backstage/plugin-permission-node                  0.5.5
  @backstage/plugin-permission-react                 0.3.4
  @backstage/plugin-proxy-backend                    0.2.24
  @backstage/plugin-scaffolder-backend               1.0.0
  @backstage/plugin-scaffolder-common                1.0.0
  @backstage/plugin-scaffolder                       1.0.0
  @backstage/plugin-search-backend-module-pg         0.3.1
  @backstage/plugin-search-backend-node              0.5.2
  @backstage/plugin-search-backend                   0.4.8
  @backstage/plugin-search-common                    0.3.2
  @backstage/plugin-search                           0.7.4
  @backstage/plugin-tech-radar                       0.5.10
  @backstage/plugin-techdocs-backend                 1.0.0
  @backstage/plugin-techdocs-node                    1.0.0
  @backstage/plugin-techdocs                         1.0.0
  @backstage/plugin-user-settings                    0.4.2
  @backstage/release-manifests                       0.0.2
  @backstage/search-common                           0.3.2
  @backstage/test-utils                              1.0.0
  @backstage/theme                                   0.2.15
  @backstage/types                                   1.0.0
  @backstage/version-bridge                          1.0.0
```

**Comment by webark** [comment]
discord thread for reference https://discord.com/channels/687207715902193673/956952078385815602

key points to note from @joeporpeglia 

> I think there's a bug in FlatRoutes. Still trying to diagnose, but I was able to fix by appending a trailing / to the /catalog route

> FlatRoutes inspects the children along with the element passed to each route and creates a nested route if any children are provided. Could be a compatibility issue with a new react-router version but not sure yet

**Comment by joeporpeglia** [comment]
Related to https://github.com/backstage/backstage/pull/10507

**Comment by webark** [comment]
one workaround is to pick a different path for the catalog-import such as `path="/catalog-import"`

**Comment by Rugvip** [comment]
This seems to be due `react-router` rating `/catalog` with a child path of `/*` higher than `/catalog-import`, even though we make sure that `/catalog-import` receives higher priority due to being listed earlier. I believe this is fixed by moving to the stable version of `react-router`, although I haven't verified that. It's the change in [`beta.6`](https://github.com/remix-run/react-router/releases/tag/v6.0.0-beta.6) to how `*` paths are treated that I believe should fix this.

Moving to `react-router` v6 stable is ongoing work and not possible just yet, see #10450 and #10451. Will verify this as part of that work too.

Another workaround for now is to also add a custom (but default) catalog import page, to counteract the route priority:

```tsx
    <Route path="/catalog-import" element={<CatalogImportPage />}>
      <DefaultImportPage />
    </Route>
```

**Comment by webark** [comment]
Should we leave this open till #10450 ?

**Comment by webark** [comment]
this is still an issue, but will be resolved once the related ticket upgrading out of react router beta 6 is done.

**Comment by benjdlambert** [comment]
@webark I've just added the `will-fix` label which will stop this thing going stale. :joy:

**Comment by webark** [comment]
This has been fixed with the updates to react router 6 Thanks so much!!
