### ISSUE TITLE
fetch:template Scaffolder Action Error: BitbucketServerUrlReader.getLastCommitShortHash

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#12827]
## Expected Behavior

When using the `fetch:template` scaffolder action it should fetch the template as expected.

## Actual Behavior

Instead, the `fetch:template` action fails with the following error:

`(http://localhost:7000/create/tasks/6072df28-487e-48fb-adf4-4cba0eb02b1e#line-3)2022-07-26T00:24:19.566Z Error: Failed to read response from https://bitbucket-server.com/rest/api/1.0/projects/projectKey/repos/repo/commits/[4](http://localhost:7000/create/tasks/6072df28-487e-48fb-adf4-4cba0eb02b1e#line-4) at _BitbucketServerUrlReader.getLastCommitShortHash (C:\source\Bitbucket\backatage\node_modules\@backstage\backend-common\dist\index.cjs.js:2035:11)[5](http://localhost:7000/create/tasks/6072df28-487e-48fb-adf4-4cba0eb02b1e#line-5) at runMicrotasks (<anonymous>)[6](http://localhost:7000/create/tasks/6072df28-487e-48fb-adf4-4cba0eb02b1e#line-6) at processTicksAndRejections (node:internal/process/task_queues:96:5)[7](http://localhost:7000/create/tasks/6072df28-487e-48fb-adf4-4cba0eb02b1e#line-7) at async _BitbucketServerUrlReader.readTree (C:\source\Bitbucket\backstage\node_modules\@backstage\backend-common\dist\index.cjs.js:1975:33)[8](http://localhost:7000/create/tasks/6072df28-487e-48fb-adf4-4cba0eb02b1e#line-8) at async UrlReaderPredicateMux.readTree (C:\source\Bitbucket\backstage\node_modules\@backstage\backend-common\dist\index.cjs.js:2929:16)[9](http://localhost:7000/create/tasks/6072df28-487e-48fb-adf4-4cba0eb02b1e#line-9)`

**Comment by awanlin** [comment]
@regicsolutions this looks to be the same error as #12740 and should be fixed by #12748

**Comment by regicsolutions** [comment]
> @regicsolutions this looks to be the same error as #12740 and should be fixed by #12748

Hi @awanlin, I bumped my @backstage/backend-common package version to the latest, and still facing the issue.

**Comment by awanlin** [comment]
@regicsolutions, sorry realized I mentioned this in my PR comment to you but not here the fix isn't out till tomorrow

**Comment by benjdlambert** [comment]
@regicsolutions this has been released now, can you do `yarn backstage-cli versions:bump --release next` and give it a try?>

**Comment by regicsolutions** [comment]
Fixed! Thanks @awanlin & @benjdlambert

**Comment by benjdlambert** [comment]
It's all @pjungermann, I just pressed the merge button :joy:

**Comment by pjungermann** [comment]
Not this time 😄  I just did a review for @awanlin 😉

**Comment by benjdlambert** [comment]
HAHAH I am so sorry @awanlin. My mind is a mess. There's just so much going on. :joy:

**Comment by awanlin** [comment]
No worries @benjdlambert, you are doing a great job running a ship that needs a crew of more then 1 person!
