### ISSUE TITLE
TechDocs flashing on navigation

### ISSUE THREAD

**Issue by rodmachen** [backstage/backstage#13696]
## Expected Behavior

As you click a navigation item, the content that you were previously viewing should remain visible (and stable) until the new content is loaded. At that time, the content should change to the new content. 

## Actual Behavior

For Tech Docs with a left-hand navigation, the content flashes multiple times as you click a navigation item. This is a poor user experience and is distracting.

## Steps to Reproduce

1. Navigate to a doc set like https://demo.backstage.io/docs/default/component/backstage/getting-started/create-an-app/.
2. Click the next link down in the left hand nav
3. Notice the blinking page.
4. Sometimes it's a bar then blinking. Sometimes just blinking.

## Context

The unnecessary blinking is distracting to the user. 

If the navigation requires a progress bar, which I assume is a round-trip to the backend service, and is sometimes seen, the content you are moving off of should still remain visible until the new content is loaded.

## Your Environment

This happens in our deployed app as well as https://demo.backstage.io/

- Browser Information: Google Chrome Version 105.0.5195.102 (Official Build) (x86_64)

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.4.0 - darwin/x64
node: v14.19.3
yarn: 1.17.3
cli:  0.17.2 (installed)

Dependencies:
  @backstage/app-defaults             0.1.9, 0.2.1, 1.0.5
  @backstage/backend-common           0.9.3, 0.13.5
  @backstage/catalog-client           1.0.4
  @backstage/catalog-model            0.9.8, 0.13.0, 0.9.10, 1.1.0
  @backstage/cli-common               0.1.9
  @backstage/cli                      0.10.0, 0.17.2
  @backstage/codemods                 0.1.38
  @backstage/config-loader            0.6.10, 0.8.1, 1.1.3
  @backstage/config                   0.1.11, 0.1.15, 1.0.1
  @backstage/core-api                 0.2.1, 0.2.23
  @backstage/core-app-api             0.2.1, 0.1.24, 0.3.1, 0.4.0, 0.5.4, 0.6.0, 1.0.5
  @backstage/core-components          0.8.1, 0.9.1, 0.9.2, 0.11.0, 0.3.3, 0.7.6, 0.8.10, 0.9.5
  @backstage/core-plugin-api          0.3.1, 0.4.0, 0.1.13, 0.2.2, 0.4.1, 0.5.0, 0.6.1, 0.7.0, 0.8.0, 1.0.5
  @backstage/core                     0.7.14
  @backstage/dev-utils                0.2.25, 1.0.5
  @backstage/errors                   0.1.5, 1.0.0, 1.1.0, 0.2.2
  @backstage/integration-react        0.1.23, 0.1.25, 1.1.3
  @backstage/integration              0.6.10, 0.7.5, 0.8.0, 1.3.0
  @backstage/plugin-api-docs          0.8.8
  @backstage/plugin-catalog-common    1.0.5
  @backstage/plugin-catalog-react     1.1.3
  @backstage/plugin-catalog           1.5.0
  @backstage/plugin-explore-react     0.0.20
  @backstage/plugin-explore           0.3.39
  @backstage/plugin-home              0.4.24
  @backstage/plugin-org               0.5.8
  @backstage/plugin-permission-common 0.5.3, 0.6.3
  @backstage/plugin-permission-react  0.3.4, 0.4.4
  @backstage/plugin-scaffolder-common 1.1.2
  @backstage/plugin-scaffolder        1.5.0
  @backstage/plugin-search-common     0.3.4, 0.3.5, 1.0.0
  @backstage/plugin-search-react      0.2.1, 1.0.1
  @backstage/plugin-search            0.5.6, 0.9.0
  @backstage/plugin-stack-overflow    0.1.4
  @backstage/plugin-techdocs-node     0.11.12
  @backstage/plugin-techdocs-react    1.0.3
  @backstage/plugin-techdocs          0.12.10, 1.3.1
  @backstage/plugin-user-settings     0.3.14, 0.4.7
  @backstage/release-manifests        0.0.4
  @backstage/search-common            0.2.4, 0.3.4
  @backstage/test-utils               0.1.24, 0.2.6, 0.3.0, 1.1.3
  @backstage/theme                    0.2.14, 0.2.9, 0.2.16
  @backstage/types                    1.0.0, 0.1.3
  @backstage/version-bridge           0.1.2, 1.0.1
```

**Comment by awanlin** [comment]
@rodmachen, can you try upgrading to the latest version? 1.5 is the latest stable and 1.6 should be out on around the 20th of September. The demo site is also on an old version (1.0.1) and I'm pretty sure this has been fixed just not sure in what version but for sure after 1.0

**Comment by rodmachen** [comment]
We are on 1.3, but this is happening on demo.backstage.io. What version is that on?

We do have a plan to upgrade to 1.6 in the next few weeks.

**Comment by kunickiaj** [comment]
This issue is still present in 1.11 and a big frustration to our users that may block further adoption. Is this on anyone's radar? I find this to happen mostly on Chrome.

**Comment by sennyeya** [comment]
Was able to verify this using Fast 3G throttling on Chrome locally. I think it's due to a race condition [when the style sheets are loading](https://github.com/backstage/backstage/blob/ac696b0bba0ecb59be7e791b0e3cbfc4bd5690f1/plugins/techdocs-react/src/component.tsx#L58). Firefox doesn't seem to have this issue because the opacity of the old element is not changing to `0` when the new page is being loaded, [here](https://github.com/backstage/backstage/blob/ac696b0bba0ecb59be7e791b0e3cbfc4bd5690f1/plugins/techdocs-react/src/component.tsx#L127).

I would check your cache settings, are you using S3/Google Storage? Maybe add a cache control to reduce chances of the race condition.

**Comment by kunickiaj** [comment]
Yes, using S3.

**Comment by kunickiaj** [comment]
> Firefox doesn't seem to have this issue because the opacity of the old element is not changing to 0 when the new page is being loaded, [here](https://github.com/backstage/backstage/blob/ac696b0bba0ecb59be7e791b0e3cbfc4bd5690f1/plugins/techdocs-react/src/component.tsx#L127).

Honestly not familiar with how this part of it works. Are you suggesting that Firefox doesn't exhibit this because it ignores this line? Trying to figure out what a permanent fix would be.

>I would check your cache settings, are you using S3/Google Storage? Maybe add a cache control to reduce chances of the race condition.

Using S3 for storage, not sure what the demo site uses but it exhibits the same behavior. Can you elaborate on this? Is the goal to simply allow the browser to cache the content for longer? That seems it would still mean users would experience this behavior on first or future visits, no?

**Comment by sennyeya** [comment]
> Are you suggesting that Firefox doesn't exhibit this because it ignores this line?
Actually not sure, I was just trying to test in Firefox and noticed that the opacity wasn't updating which gave the illusion that it didn't have the same problem.

> Is the goal to simply allow the browser to cache the content for longer?
I believe so. At least on the demo site, the style sheets that get loaded are the exact same ones that were previously loaded but the default behaviour is return a 304 instead of allowing the browser to cache the resources. The extra round trip time triggers the race condition (I think). 

I'm honestly not sure what a permanent fix would look like, maybe @camilaibs could help? I think she worked on the last iteration.

**Comment by kunickiaj** [comment]
Ah interesting. I can confirm that on my setup I also get a 304 when the flashing occurs.

**Comment by sennyeya** [comment]
@camilaibs Any thoughts on this? I think I've pinpointed what's causing the issue, but not sure what the solution would look like on our side. As you worked on the last fix, any help would be appreciated :)

**Comment by sennyeya** [comment]
@camilaibs Hadn't realized this had closed, I think this is still an issue.

**Comment by milanmayr** [comment]
This docs behavior is definitely rough to see, and I agree that it may hinder adoption. @hoyon do you think you could create a PR with the changes you've already made, even if it doesn't contain a total fix yet?

**Comment by jenreiher-bcgov** [comment]
Just wanted to comment here that this is resulting in a delay in adoption by other teams with docs within our organization. It would be great to get a fix!

**Comment by alper98** [comment]
Still an issue, and it hinders adoption

**Comment by patrick-bercow** [comment]
any updates on this? we got the same issue 

OS:   Windows_NT 10.0.19045 - win32/x64
node: v18.12.0
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.14.0

Dependencies:
  @backstage/app-defaults                               1.3.1
  @backstage/backend-app-api                            0.4.3, 0.5.10, 0.7.0
  @backstage/backend-common                             0.18.5, 0.19.9, 0.20.1, 0.21.7
  @backstage/backend-dev-utils                          0.1.1, 0.1.3, 0.1.4
  @backstage/backend-plugin-api                         0.5.2, 0.6.17, 0.6.9
  @backstage/backend-tasks                              0.5.14, 0.5.2, 0.5.22
  @backstage/backend-test-utils                         0.2.4
  @backstage/catalog-client                             1.4.1, 1.5.2, 1.6.4
  @backstage/catalog-model                              1.3.0, 1.4.3, 1.4.5
  @backstage/cli-common                                 0.1.12, 0.1.13
  @backstage/cli-node                                   0.1.0, 0.2.2, 0.2.5
  @backstage/cli                                        0.22.7
  @backstage/config-loader                              1.3.0, 1.6.1, 1.8.0
  @backstage/config                                     1.0.7, 1.1.1, 1.2.0
  @backstage/core-app-api                               1.8.0
  @backstage/core-components                            0.12.5, 0.13.1, 0.13.10
  @backstage/core-plugin-api                            1.5.1, 1.8.2
  @backstage/dev-utils                                  1.0.15
  @backstage/errors                                     1.1.5, 1.2.3, 1.2.4
  @backstage/eslint-plugin                              0.1.3
  @backstage/frontend-plugin-api                        0.5.0
  @backstage/integration-aws-node                       0.1.12, 0.1.3, 0.1.8
  @backstage/integration-react                          1.1.13, 1.1.23
  @backstage/integration                                1.10.0, 1.4.5, 1.8.0
  @backstage/plugin-api-docs                            0.9.3
  @backstage/plugin-app-backend                         0.3.45
  @backstage/plugin-auth-backend                        0.18.3
  @backstage/plugin-auth-node                           0.2.14, 0.3.2, 0.4.12, 0.4.3
  @backstage/plugin-badges-backend                      0.2.0
  @backstage/plugin-badges                              0.2.42
  @backstage/plugin-catalog-backend-module-gitlab       0.2.1
  @backstage/plugin-catalog-backend-module-ldap         0.5.33
  @backstage/plugin-catalog-backend                     1.9.1
  @backstage/plugin-catalog-common                      1.0.13, 1.0.20, 1.0.22
  @backstage/plugin-catalog-graph                       0.2.30
  @backstage/plugin-catalog-import                      0.9.8
  @backstage/plugin-catalog-node                        1.11.1, 1.3.6
  @backstage/plugin-catalog-react                       1.6.0, 1.9.3
  @backstage/plugin-catalog                             1.11.0
  @backstage/plugin-devtools-backend                    0.1.0
  @backstage/plugin-devtools-common                     0.1.0
  @backstage/plugin-devtools                            0.1.0
  @backstage/plugin-github-actions                      0.5.18
  @backstage/plugin-home                                0.5.2
  @backstage/plugin-kubernetes-backend                  0.11.0
  @backstage/plugin-kubernetes-common                   0.6.3
  @backstage/plugin-kubernetes                          0.9.0
  @backstage/plugin-org                                 0.6.8
  @backstage/plugin-permission-backend                  0.5.20
  @backstage/plugin-permission-common                   0.7.12, 0.7.13, 0.7.5
  @backstage/plugin-permission-node                     0.7.20, 0.7.28, 0.7.8
  @backstage/plugin-permission-react                    0.4.12, 0.4.19
  @backstage/plugin-proxy-backend                       0.2.39
  @backstage/plugin-scaffolder-backend                  1.14.0
  @backstage/plugin-scaffolder-common                   1.3.0, 1.4.5
  @backstage/plugin-scaffolder-node                     0.1.3
  @backstage/plugin-scaffolder-react                    1.4.0, 1.7.1
  @backstage/plugin-scaffolder                          1.13.1, 1.17.1
  @backstage/plugin-search-backend-module-catalog       0.1.1
  @backstage/plugin-search-backend-module-pg            0.5.6
  @backstage/plugin-search-backend-module-techdocs      0.1.1
  @backstage/plugin-search-backend-node                 1.2.1
  @backstage/plugin-search-backend                      1.3.1
  @backstage/plugin-search-common                       1.2.3, 1.2.10, 1.2.11
  @backstage/plugin-search-react                        1.6.0
  @backstage/plugin-search                              1.3.0
  @backstage/plugin-shortcuts                           0.3.10
  @backstage/plugin-sonarqube-backend                   0.1.10
  @backstage/plugin-sonarqube-react                     0.1.5
  @backstage/plugin-sonarqube                           0.6.7
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.29
  @backstage/plugin-tech-insights-backend               0.5.11
  @backstage/plugin-tech-insights-common                0.2.10
  @backstage/plugin-tech-insights-node                  0.4.3
  @backstage/plugin-tech-insights                       0.3.10
  @backstage/plugin-tech-radar                          0.6.4
  @backstage/plugin-techdocs-backend                    1.6.2
  @backstage/plugin-techdocs-module-addons-contrib      1.0.13
  @backstage/plugin-techdocs-node                       1.7.1
  @backstage/plugin-techdocs-react                      1.1.15, 1.1.6
  @backstage/plugin-techdocs                            1.6.2
  @backstage/plugin-user-settings                       0.7.3
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.3.1
  @backstage/theme                                      0.2.19, 0.3.0, 0.4.4, 0.5.0
  @backstage/types                                      1.0.2, 1.1.1
  @backstage/version-bridge                             1.0.4, 1.0.7

**Comment by benjdlambert** [comment]
@backstage/techdocs-maintainers think this is still relevant

**Comment by szboynono** [comment]
any updates on the flickering issue? it's been 2 years ..

**Comment by awanlin** [comment]
Hi, would be great to get more feedback on this using the latest Backstage version including examples and perhaps a video example. I can't reproduce this on the Demo site but if someone can that's great. Also, very much open to contributions!

I do see this related issue on the Demo site which might be masking the flickering: https://github.com/backstage/backstage/issues/25504

**Comment by aramissennyeydd** [comment]
@awanlin It's pretty straightforward to duplicate on the demo site, https://demo.backstage.io/docs/default/component/backstage/features/software-catalog/descriptor-format/ with 3G toggling. You can see this happen in the last few seconds of this video,

https://github.com/backstage/backstage/assets/159921952/bd4d6559-912f-4774-a9cb-6ed043cc92b0

Even with the cache enabled, this is happening and you can see in my DevTools that I'm getting an S3 response for _every_ CSS request for `https://demo.backstage.io/api/techdocs/static/docs/default/component/backstage/assets/stylesheets/main.6543a935.min.css`, so it's weirdly not being cached which I think is causing this bug.

**Comment by awanlin** [comment]
Awesome, many thanks @aramissennyeydd. I think I was very focused on expecting "flickering" but I for sure see this delayed loading bar when I load each page. 👍

**Comment by Fuglen** [comment]
We are experiencing a different kind of "flickering" which is a bit faster.
We are using a minIO bucket for storage and is always placed right next to our Backstage.
I have tried to use the cache (redis/memory) for TechDocs but couldn't get it working.

https://github.com/backstage/backstage/assets/6181362/dd62053f-23ff-4943-9d5a-35756191c00e

**Comment by Fuglen** [comment]
Great to hear @awanlin, we are currently on 1.28.3

**Comment by johnphilip283** [comment]
Hi @Fuglen - would you be able to open up your network tab and provide another video just to make sure that the cause of your flickering is due to the same re-requested CSS? Just to help us confirm that this is indeed caused by the same bug.

**Comment by Fuglen** [comment]
Really awesome to see a PR to possibly fix this 🙌
@johnphilip283 I have just updated my previous comment with a new video :)

**Comment by awanlin** [comment]
Hi @aramissennyeydd, the PR just got merged today but I was wondering if you'd be open to trying the nightly release after tomorrow? The change was just in `@backstage/plugin-techdocs` so it should be pretty easy to get in place: https://www.npmjs.com/package/@backstage/plugin-techdocs?activeTab=versions

**Note: to be super clear the fix is NOT in the nightly release yet, that will happen around 9:30pm CST.**

**Comment by aramissennyeydd** [comment]
@awanlin, I won't be able to test this until after the weekend, but I can take a look at the nightly release then.

**Comment by awanlin** [comment]
Thanks @aramissennyeydd, for sure, sorry if my wording was poor, not expecting you to work on the weekend!

**Comment by szboynono** [comment]
Thanks for the PR, it definitely made an improvement on the flickering issue. But the issue still persist, 
To replicate it: go to https://demo.backstage.io/docs/default/component/backstage/plugins/create-a-plugin/ , set to a slower network, like fast 3G and try to navigate between pages within the techdoc.

Yes I think it is the opacity set to 0 thing that is causing part of it, is it possible to give us an option to disable that?
