### ISSUE TITLE
🐛 Bug Report: Azure DevOps README not working

### ISSUE THREAD

**Issue by jmezach** [backstage/backstage#14831]
### 📜 Description

I've followed the instructions as outlined [here](https://github.com/backstage/backstage/blob/master/plugins/azure-devops/README.md#git-readme) to get the README.md from my Azure Repos repository, but I'm receiving an error when I open my entity overview page.

### 👍 Expected behavior

My entity overview page displays the entity's README.md from Azure Repos.

### 👎 Actual Behavior with Screenshots

Opening the overview of my entity gives me the following error:

![Screenshot 2022-11-24 at 11 55 08](https://user-images.githubusercontent.com/1225489/203766870-c62c07b4-c08d-49fc-bc8d-085c3b52c9ba.png)

In the logs I'm seeing the following:

```
[1] 2022-11-24T10:48:36.448Z backstage error Cannot read properties of undefined (reading 'readUrl') type=errorHandler stack=TypeError: Cannot read properties of undefined (reading 'readUrl')
[1]     at AzureDevOpsApi.getReadme (/Users/jonathanm/Code/demos/demo-backstage-app/node_modules/@backstage/plugin-azure-devops-backend/dist/index.cjs.js:487:43)
[1]     at /Users/jonathanm/Code/demos/demo-backstage-app/node_modules/@backstage/plugin-azure-devops-backend/dist/index.cjs.js:770:41
[1]     at handleReturn (/Users/jonathanm/Code/demos/demo-backstage-app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
[1]     at /Users/jonathanm/Code/demos/demo-backstage-app/node_modules/express-promise-router/lib/express-promise-router.js:64:7
[1]     at handleReturn (/Users/jonathanm/Code/demos/demo-backstage-app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
[1]     at /Users/jonathanm/Code/demos/demo-backstage-app/node_modules/express-promise-router/lib/express-promise-router.js:64:7
[1]     at Layer.handle [as handle_request] (/Users/jonathanm/Code/demos/demo-backstage-app/node_modules/express/lib/router/layer.js:95:5)
[1]     at next (/Users/jonathanm/Code/demos/demo-backstage-app/node_modules/express/lib/router/route.js:144:13)
[1]     at Route.dispatch (/Users/jonathanm/Code/demos/demo-backstage-app/node_modules/express/lib/router/route.js:114:3)
[1]     at Layer.handle [as handle_request] (/Users/jonathanm/Code/demos/demo-backstage-app/node_modules/express/lib/router/layer.js:95:5)
```

### 👟 Reproduction steps

1. Follow the steps described [here](https://github.com/backstage/backstage/blob/master/plugins/azure-devops/README.md#git-readme)
2. Open the entity overview page
3. See the error above

### 📃 Provide the context for the Bug.

I'm currently experimenting with Backstage to see if it can help my organization. It would be really beneficial to have the README's in there.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @jmezach, looks like you hit a spot where we need to find some better balance in the docs. When this feature was added it included a backend change to add support for the `UrlReader` which is the error you are seeing. Looks like we never updated the backend docs for this either sadly.

Here's the fix though, in your `packages/backend/src/plugins/azure-devops.ts` add the following line:

```diff
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return createRouter({
    logger: env.logger,
    config: env.config,
+    reader: env.reader,
  });
}
```

If you'd like to create PR updating the README for both the frontend and backend that would be wonderful!

**Comment by jmezach** [comment]
Thanks @awanlin, I just made this change on my machine and that does indeed work.

I'm a little bit busy today, but I'll try to send in a PR when I have some time available.

**Comment by jhaals** [comment]
fixed by https://github.com/backstage/backstage/pull/14921

**Comment by mpicard** [comment]
This is still an issue but the reader was removed from the RouterOptions interface, what do I do? I followed the instructions of the latest docs
