### ISSUE TITLE
🐛 Bug Report: Backend failed to start up SqliteError: database is locked

### ISSUE THREAD

**Issue by benkeil** [backstage/backstage#15044]
### 📜 Description

I try to use the sqlite database with a file and get this error:

```
[1] Backend failed to start up SqliteError: create table `backstage_backend_tasks__knex_migrations` (`id` integer not null primary key autoincrement, `name` varchar(255), `batch` integer, `migration_time` datetime) - database is locked
[1]     at Client_BetterSQLite3._query (/Users/Benedikt.Keil/development/github.com/otto-ec/si_backstage/src/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
[1]     at executeQuery (/Users/Benedikt.Keil/development/github.com/otto-ec/si_backstage/src/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
[1]     at Client_BetterSQLite3.query (/Users/Benedikt.Keil/development/github.com/otto-ec/si_backstage/src/node_modules/knex/lib/client.js:146:12)
[1]     at Runner.query (/Users/Benedikt.Keil/development/github.com/otto-ec/si_backstage/src/node_modules/knex/lib/execution/runner.js:123:36)
[1]     at Runner.queryArray (/Users/Benedikt.Keil/development/github.com/otto-ec/si_backstage/src/node_modules/knex/lib/execution/runner.js:217:21)
[1]     at ensureConnectionCallback (/Users/Benedikt.Keil/development/github.com/otto-ec/si_backstage/src/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19)
[1]     at Runner.ensureConnection (/Users/Benedikt.Keil/development/github.com/otto-ec/si_backstage/src/node_modules/knex/lib/execution/runner.js:300:20)
[1]     at async Runner.run (/Users/Benedikt.Keil/development/github.com/otto-ec/si_backstage/src/node_modules/knex/lib/execution/runner.js:30:19)
[1]     at async listCompleted (/Users/Benedikt.Keil/development/github.com/otto-ec/si_backstage/src/node_modules/knex/lib/migrations/migrate/migration-list-resolver.js:12:3)
[1]     at async Promise.all (index 1) {
[1]   code: 'SQLITE_BUSY'
[1] }
```

### 👍 Expected behavior

The system should start

### 👎 Actual Behavior with Screenshots

Try one of there configs

```yaml
backend:
  database:
    client: better-sqlite3
    plugin:
      test:
        connection:
          directory: database
          filename: catalog.sqlite
```

or

```yaml
backend:
  database:
    client: better-sqlite3
    connection:
      directory: database
```

### 👟 Reproduction steps

1. Configure the database
2. start the application

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
I'm not able to reproduce this, I tried the following config:

```yaml
backend:
  database:
    client: better-sqlite3
    connection:
      directory: database
```

**Comment by danieljamesscott** [comment]
I am also seeing the error when using a directory + file for the DB

**Comment by jhaals** [comment]
Would you be able to include some reproduction steps to help us debug this issue as we're not able to reproduce it with an app created using `npx @backstage/create-app` 🙏

**Comment by danieljamesscott** [comment]
Hmm. Yes. With a newly created app, it works fine. Maybe I have a plugin which is incorrectly managing the database connection? Do you have a link to the code which opens the database connection so I can see if any plugins are using it.

**Comment by freben** [comment]
@danieljamesscott The only thing that plugins can generally do, is to call [`getClient()`](https://github.com/backstage/backstage/blob/10c9450007e4584b9388ddb79048c9add737e496/packages/backend-common/src/database/types.ts#L32) on the `PluginDatabaseManager` that they've been given by the backend. This [is implemented](https://github.com/backstage/backstage/blob/10c9450007e4584b9388ddb79048c9add737e496/packages/backend-common/src/database/DatabaseManager.ts#L101) by the `DatabaseManger` class, and it [is meant to ensure](https://github.com/backstage/backstage/blob/10c9450007e4584b9388ddb79048c9add737e496/packages/backend-common/src/database/DatabaseManager.ts#L311) to never try to create the same database twice, instead returning the same exact connection pool over and over if asked multiple times.

As long as unique plugin IDs are used for each plugin, and as long as the `directory` mode is used, and as long as you don't have any odd overrides in place that accidentally make the file names overlap - this should not lead to conflicts.

The deduplication code was [added on October 3rd](https://github.com/backstage/backstage/pull/13971), so older releases of Backstage would indeed risk suffering from the problem you describe.

**Comment by danieljamesscott** [comment]
OK. I think I have figured out some steps to reproduce it. Possibly it's something to do with scheduled tasks starting up for scanning GitHub?

1. Create a new app using `npx @backstage/create-app`
2. Modify `app-config.yaml` to use `database: directory` instead of `:memory:`
3. `yarn install && yarn dev` to confirm that it works.
4. Install the GitHub catalog plugin `yarn add --cwd packages/backend @backstage/plugin-catalog-backend-module-github`
5. Add both the `GithubEntityProvider` and `GithubOrgEntityProvider` (The error did not show when only 1 of these was enabled.)
6. `yarn dev`

Error:

```
[1] Backend failed to start up SqliteError: create table `backstage_backend_tasks__knex_migrations` (`id` integer not null primary key autoincrement, `name` varchar(255), `batch` integer, `migration_time` datetime) - database is locked
```

**Comment by freben** [comment]
Could it be that you are missing an `await` on a promise when creating those scheduled providers? Such that it tries to run two migrations at the same time.

I'll add here too, that we don't officially support file based sqlite. The entire driver was originally only intended for quick and dirty in-memory local dev and testing use. The only officially supported drivers are postgres, and in-memory sqlite. If you or others in the community find bugs with the use of on-disk sqlite and fix them, we're of course super happy to keep up that best-effort support and help get those pull requests merged.

**Comment by mtlewis** [comment]
Just flagging that I stumbled on this too - it seems to me that there's a problematic interaction between the recommended way of using integrations like the `GithubOrgEntityProvider` and database migrations. It seems like there's nothing a consumer of this class can do when using the built-in `TaskScheduler` support to prevent it from asynchronously starting to schedule the task when it's constructed. This means that in some cases it will attempt to schedule the task while the database migration built into the `CatalogBuilder` is happening.

I'm not sure why it's only apparent for file-based SQLite though - perhaps because all the tables live in a single file, and therefore all get locked at once? The only workaround I could come up with is switching the schedule to `manual`, and manually scheduling the task myself after `CatalogBuilder#build` has finished (and therefore the database migrations are done).

**Comment by Rugvip** [comment]
@mtlewis huh, that seems like a bug or otherwise unexpected behavior with knex migrations or something like it O_o. The database migrations are supposed to have run to completion before the entity providers are connected (scheduled). Is it possible to reproduce this simply by combining the `GithubOrgEntityProvider` with file-based SQLite?

**Comment by ctasada** [comment]
Using Backstage 1.13.0 I get the same error

I replicated the steps provided by @danieljamesscott at https://github.com/backstage/backstage/issues/15044#issuecomment-1359267272

I used `yarn add --cwd packages/backend @backstage/plugin-catalog-backend-module-gitlab` instead of `github`

Full stacktrace is
```
[1] 2023-04-24T08:03:42.234Z catalog info Performing database migration type=plugin
[1] Backend failed to start up SqliteError: create table `backstage_backend_tasks__knex_migrations` (`id` integer not null primary key autoincrement, `name` varchar(255), `batch` integer, `migration_time` datetime) - database is locked
[1]     at Client_BetterSQLite3._query (/Users/carlostasada/source/backstage-test/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
[1]     at executeQuery (/Users/carlostasada/source/backstage-test/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
[1]     at Client_BetterSQLite3.query (/Users/carlostasada/source/backstage-test/node_modules/knex/lib/client.js:146:12)
[1]     at Runner.query (/Users/carlostasada/source/backstage-test/node_modules/knex/lib/execution/runner.js:123:36)
[1]     at Runner.queryArray (/Users/carlostasada/source/backstage-test/node_modules/knex/lib/execution/runner.js:217:21)
[1]     at ensureConnectionCallback (/Users/carlostasada/source/backstage-test/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19)
[1]     at Runner.ensureConnection (/Users/carlostasada/source/backstage-test/node_modules/knex/lib/execution/runner.js:300:20)
[1]     at async Runner.run (/Users/carlostasada/source/backstage-test/node_modules/knex/lib/execution/runner.js:30:19)
[1]     at async listCompleted (/Users/carlostasada/source/backstage-test/node_modules/knex/lib/migrations/migrate/migration-list-resolver.js:12:3)
[1]     at async Promise.all (index 1) {
[1]   code: 'SQLITE_BUSY'
[1] }
```

**Comment by markopolo123** [comment]
came here to report the same thing on backstage 1.13.0 and adding just the `GithubOrgEntityProvider` entity provider, again when using sqlite not in memory. Can't replicate with in memory sqlite. 

```bash
[1] 2023-04-28T09:45:33.245Z catalog info Performing database migration type=plugin
[1] Backend failed to start up SqliteError: create table `backstage_backend_tasks__knex_migrations` (`id` integer not null primary key autoincrement, `name` varchar(255), `batch` integer, `migration_time` datetime) - database is locked
[1]     at Client_BetterSQLite3._query (/Users/msh/Documents/idp/my-backstage-app/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:38)
[1]     at executeQuery (/Users/msh/Documents/idp/my-backstage-app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
[1]     at Client_BetterSQLite3.query (/Users/msh/Documents/idp/my-backstage-app/node_modules/knex/lib/client.js:146:12)
[1]     at Runner.query (/Users/msh/Documents/idp/my-backstage-app/node_modules/knex/lib/execution/runner.js:123:36)
[1]     at Runner.queryArray (/Users/msh/Documents/idp/my-backstage-app/node_modules/knex/lib/execution/runner.js:217:21)
[1]     at ensureConnectionCallback (/Users/msh/Documents/idp/my-backstage-app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19)
[1]     at Runner.ensureConnection (/Users/msh/Documents/idp/my-backstage-app/node_modules/knex/lib/execution/runner.js:300:20)
[1]     at async Runner.run (/Users/msh/Documents/idp/my-backstage-app/node_modules/knex/lib/execution/runner.js:30:19)
[1]     at async listCompleted (/Users/msh/Documents/idp/my-backstage-app/node_modules/knex/lib/migrations/migrate/migration-list-resolver.js:12:3)
[1]     at async Promise.all (index 1) {
[1]   code: 'SQLITE_BUSY'
[1] }
```

**Comment by omerfarukdogan** [comment]
Same issue with `BitbucketServerEntityProvider`.

**Comment by omerfarukdogan** [comment]
@Rugvip Is it possible to reopen this issue? It affects our development environment negatively since we can't use a persistent storage without installing PostgreSQL. Everytime we restart the backend, we have to wait for the database to be populated before even logging in.

**Comment by prateek45** [comment]
Hi All,
I am facing the same error with GITLAB:

```
Backend failed to start up SqliteError: create table `backstage_backend_tasks__knex_migrations` (`id` integer not null primary key autoincrement, `name` varchar(255), `batch` integer, `migration_time` datetime) - database is locked
[1]     at Client_BetterSQLite3._query (C:\Users\p1356588\Desktop\Projects\bast\node_modules\knex\lib\dialects\better-sqlite3\index.js:44:38)
[1]     at executeQuery (C:\Users\p1356588\Desktop\Projects\bast\node_modules\knex\lib\execution\internal\query-executioner.js:37:17)
[1]     at Client_BetterSQLite3.query (C:\Users\p1356588\Desktop\Projects\bast\node_modules\knex\lib\client.js:154:12)
[1]     at Runner.query (C:\Users\p1356588\Desktop\Projects\bast\node_modules\knex\lib\execution\runner.js:141:36)
[1]     at Runner.queryArray (C:\Users\p1356588\Desktop\Projects\bast\node_modules\knex\lib\execution\runner.js:235:21)
[1]     at ensureConnectionCallback (C:\Users\p1356588\Desktop\Projects\bast\node_modules\knex\lib\execution\internal\ensure-connection-callback.js:11:19)      
[1]     at Runner.ensureConnection (C:\Users\p1356588\Desktop\Projects\bast\node_modules\knex\lib\execution\runner.js:318:20)
[1]     at async Runner.run (C:\Users\p1356588\Desktop\Projects\bast\node_modules\knex\lib\execution\runner.js:30:19)
[1]     at async listCompleted (C:\Users\p1356588\Desktop\Projects\bast\node_modules\knex\lib\migrations\migrate\migration-list-resolver.js:12:3)
[1]     at async Promise.all (index 1)
[1]     at async Migrator.latest (C:\Users\p1356588\Desktop\Projects\bast\node_modules\knex\lib\migrations\migrate\Migrator.js:63:29)
[1]     at async migrateBackendTasks (C:\Users\p1356588\Desktop\Projects\bast\node_modules\@backstage\backend-tasks\dist\index.cjs.js:91:3)
[1]     at async PluginTaskSchedulerImpl.<anonymous> (C:\Users\p1356588\Desktop\Projects\bast\node_modules\@backstage\backend-tasks\dist\index.cjs.js:676:9)    
[1]     at async PluginTaskSchedulerImpl.scheduleTask (C:\Users\p1356588\Desktop\Projects\bast\node_modules\@backstage\backend-tasks\dist\index.cjs.js:543:20)  
[1]     at async Object.run (C:\Users\p1356588\Desktop\Projects\bast\node_modules\@backstage\backend-tasks\dist\index.cjs.js:569:9)
[1]     at async GitlabOrgDiscoveryEntityProvider.connect (C:\Users\p1356588\Desktop\Projects\bast\node_modules\@backstage\plugin-catalog-backend-module-gitlab\dist\index.cjs.js:226:5) {
[1]   code: 'SQLITE_BUSY'
[1] }
```

I have added Postgress database connection in app-config.local.yaml:


'''
backend:
  database:
    connection:
      host: localhost
      # Default postgresql port is 5432; this might be different for your installation
      port: 5432
      user: postgres
      # Replace the password below with your postgresql password:
      password: <password>
'''


and my catalog.ts is:

'''
import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
import { Router } from 'express';
/* packages/backend/src/plugins/catalog.ts */
import { GitlabOrgDiscoveryEntityProvider } from '@backstage/plugin-catalog-backend-module-gitlab';
import { PluginEnvironment } from '../types';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addProcessor(new ScaffolderEntitiesProcessor());
  /** Adding Gitlab Configuration */
  builder.addEntityProvider(
    ...GitlabOrgDiscoveryEntityProvider.fromConfig(env.config, {
      logger: env.logger,
      // optional: alternatively, use scheduler with schedule defined in app-config.yaml
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: { minutes: 30 },
        timeout: { minutes: 3 },
      }),
    }),
  );

  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}
'''

Please help

**Comment by benjdlambert** [comment]
@prateek45 it looks like you're still using `better-sqlite` as the client.

You will need to define `client: pg` in the `backend.database` section of the `app-config.yaml` too

**Comment by rmartine-ias** [comment]
unstale

**Comment by KillDozerX2** [comment]
Reopening this as we're facing the same issue.

**Comment by benjdlambert** [comment]
@KillDozerX2 what's the issue your facing? We've not had a reply on this issue for quite some time after https://github.com/backstage/backstage/issues/15044#issuecomment-1752841916

Can you also list your config?

**Comment by mario-mui** [comment]
<img width="1011" alt="image" src="https://github.com/backstage/backstage/assets/7720722/19662716-c048-4858-8878-7fa4f4b03650">
run in docker with better-sqlite3, I got this error.

yarn dev with better-sqlite3 works fine and run in docker with pg also works fine

**Comment by tudi2d** [comment]
closing this as the following should fix it:

> it looks like you're still using better-sqlite as the client.
>
> You will need to define client: pg in the backend.database section of the app-config.yaml too

**Comment by gozdebudak** [comment]
we're still getting error with these configurations

  ```
database:
    client: better-sqlite3
    connection:
      directory: ./dbs
    knexConfig:
      pool:
        min: 0
        max: 1
```

`[1] Backend failed to start up SqliteError: create table backstage_backend_tasks__knex_migrations (id integer not null primary key autoincrement, name varchar(255), batch integer, migration_time datetime) - database is locked`

**Comment by freben** [comment]
@gozdebudak We don't consider on-disk sqlite a supported option, and we're very wary of trying to introduce official support for it because of some complexities such as this one. Only in-memory sqlite, exclusively for quick local testing and debugging, is supported.

May I ask why you were using this in your setup?

**Comment by gozdebudak** [comment]
@freben We also want to use in-memory sqlite for local testing and debugging. We are using non-persistant memory sqlite and everytime we restart the backend by adding or deleting code lines, we have to wait for the database to be populated. Also, our local environments are populated by our scm tool's test environment. So, if a bug occurs in this environment, we have to wait for the problem to be resolved to continue development. 

If we could use a persistent storage, our development will not be interrupted.

**Comment by freben** [comment]
I thought our sqlite databases were meant to be serialized and deserialized automatically during reloads in local dev (ping @Rugvip). Oh but it seems you're on the old backend system though, I may misremember how that was implemented - do you have it set up for hot reloading? For example https://github.com/backstage/backstage/blob/eeb5b782de04ef2f3561a22366acf909146dd881/packages/backend-legacy/src/index.ts#L169

I sometimes choose to run a local docker postgres for local dev also.

**Comment by awanlin** [comment]
Just wanted to add "Plus 1" to running Postgres in a Docker container locally, that's worked very well for me. 👍

**Comment by gozdebudak** [comment]
I checked and we have that line for hot reloading but it's still not working. We can not run docker on local because of company restrictions. Our Backstage version is 1.13.0, is there any chance to solve that with version upgrade?

**Comment by benjdlambert** [comment]
@gozdebudak there's no guarantee, but that version is unfortunately quite old, so it's possible! :pray:
