### ISSUE TITLE
🐛 Bug Report: TechDocs CLI app is missing search query service implementation

### ISSUE THREAD

**Issue by Remyapraveen** [backstage/backstage#15981]
### 📜 Description

Hi, When trying to create techdocs using the 'mkdocs.yml' locally using the command
 "npx @techdocs/cli generate --docker-image  spotify/techdocs" , the folder site is generated to the root directory and success message is shown in the terminal. But when trying to serve the techdocs it shows error message in the local server.  
I have attached the screen shot of my VSC and also the error message screenshots.
![image](https://user-images.githubusercontent.com/93478132/214771997-42520ccd-88a2-40d5-b1d9-179c4a130201.png)

### 👍 Expected behavior

The docs that are generated should be displayed while serving them locally. 

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/93478132/214772099-01c09e5b-fd24-4a98-8a1e-feb8402764df.png)

### 👟 Reproduction steps

1. From any backstage app, create a 'mkdocs.yml' file in the root of a component with adequate details like 

site_name: 'preffered Name'
site_description: "Any description"

nav:
  - Home: 'index.md'
  
plugins:
  - techdocs-core

2. Next create the above-mentioned documents such as index.md under a folder 'docs' in the root directory. 
3. Now, in the "catalog-info.yaml' file add in the "annotations:" on where to find the techdocs. Since we are storing it internally, the link can be given as below. 
 
annotations:
  backstage.io/techdocs-ref: dir:.

4. Now we can generate the techdocs using the command "npx @techdocs/cli generate --docker-image spotify/techdocs".
5. When you see the success message "Done" and the new folder name "site" created in the root directory. We are ready to serve and view the docs locally. 
6. We can use the command "npx @techdocs/cli serve --docker-image spotify/techdocs" to view the docs. 

### 📃 Provide the context for the Bug.

The stack trace and the error that I am receiving while generating and viewing the techdocs locally. 

Error
Error

Message
No implementation available for apiRef{plugin.search.queryservice}

Stack Trace
Error: No implementation available for apiRef{plugin.search.queryservice}
    at ne (http://localhost:3000/static/main.78e87b92.js:30:85915)
    at Se (http://localhost:3000/static/main.78e87b92.js:31:167399)
    at Ge (http://localhost:3000/static/main.78e87b92.js:31:168601)
    at ui (http://localhost:3000/static/module-react-dom.5abdac04.js:12:52896)
    at ws (http://localhost:3000/static/module-react-dom.5abdac04.js:16:8700)
    at hs (http://localhost:3000/static/module-react-dom.5abdac04.js:16:937)
    at Za (http://localhost:3000/static/module-react-dom.5abdac04.js:16:868)
    at $t (http://localhost:3000/static/module-react-dom.5abdac04.js:16:726)
    at Mi (http://localhost:3000/static/module-react-dom.5abdac04.js:14:10871)
    at http://localhost:3000/static/module-react-dom.5abdac04.js:12:38720

### 🖥️ Your Environment

yarn run v1.22.19
$ "C:\Users\remya\OneDrive\Desktop\Developer VSC\bc_devportal\devportal\node_modules\.bin\backstage-cli" info
OS:   Windows_NT 10.0.22621 - win32/x64
node: v18.13.0
yarn: 1.22.19
cli:  0.22.1 (installed)
backstage:  1.10.0

Dependencies:
  @backstage/app-defaults                          1.1.0
  @backstage/backend-app-api                       0.3.1
  @backstage/backend-common                        0.18.1
  @backstage/backend-plugin-api                    0.3.1
  @backstage/backend-tasks                         0.4.2
  @backstage/catalog-client                        1.3.0
  @backstage/catalog-model                         1.1.5
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.1
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.4.0
  @backstage/core-components                       0.12.3
  @backstage/core-plugin-api                       1.3.0
  @backstage/errors                                1.1.4
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.9
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.8.14
  @backstage/plugin-app-backend                    0.3.41
  @backstage/plugin-auth-backend                   0.17.4
  @backstage/plugin-auth-node                      0.2.10
  @backstage/plugin-catalog-backend                1.7.1
  @backstage/plugin-catalog-common                 1.0.10
  @backstage/plugin-catalog-graph                  0.2.26
  @backstage/plugin-catalog-import                 0.9.4
  @backstage/plugin-catalog-node                   1.3.2
  @backstage/plugin-catalog-react                  1.2.4
  @backstage/plugin-catalog                        1.7.2
  @backstage/plugin-github-actions                 0.5.14
  @backstage/plugin-org                            0.6.4
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.4
  @backstage/plugin-permission-react               0.4.9
  @backstage/plugin-proxy-backend                  0.2.35
  @backstage/plugin-scaffolder-backend             1.10.1
  @backstage/plugin-scaffolder-common              1.2.4
  @backstage/plugin-scaffolder-react               1.0.1
  @backstage/plugin-scaffolder                     1.10.1
  @backstage/plugin-search-backend-module-pg       0.5.2
  @backstage/plugin-search-backend-node            1.1.2
  @backstage/plugin-search-backend                 1.2.2
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.4.0
  @backstage/plugin-search                         1.0.7
  @backstage/plugin-tech-radar                     0.6.0
  @backstage/plugin-techdocs-backend               1.5.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.9
  @backstage/plugin-techdocs-node                  1.4.5
  @backstage/plugin-techdocs-react                 1.1.2
  @backstage/plugin-techdocs                       1.4.3
  @backstage/plugin-user-settings                  0.6.2
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.4
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
Done in 1.11s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
This looks like you need to render the `SearchPage` component from '@backstage/plugin-search` in your `packages/app/src/App.tsx`

Please take a read of this [getting started](https://backstage.io/docs/features/search/getting-started) docs for more information about setting up the search plugin 👍

**Comment by Remyapraveen** [comment]
Hi @benjdlambert , Thank you for your response.  But with whatever I understand, it seems I already have the `SearchPage` in my packages/app/src/App.tsx. Could you please confirm if this is what you are suggesting? I am actually new to this, so please do bear with me if I am wrong. 
![image](https://user-images.githubusercontent.com/93478132/214821757-a403d0f3-7b12-4121-a03b-9af4dc935453.png)

**Comment by benjdlambert** [comment]
@Remyapraveen can i see the rest of that file? The most important bit is the usage of that import further down the file.

**Comment by Remyapraveen** [comment]
Hi @benjdlambert, here's the content of the file. 

import React from 'react';
import { Navigate, Route } from 'react-router-dom';
import { apiDocsPlugin, ApiExplorerPage } from '@backstage/plugin-api-docs';
import {
  CatalogEntityPage,
  CatalogIndexPage,
  catalogPlugin,
} from '@backstage/plugin-catalog';
import {
  CatalogImportPage,
  catalogImportPlugin,
} from '@backstage/plugin-catalog-import';
import { ScaffolderPage, scaffolderPlugin } from '@backstage/plugin-scaffolder';
import { orgPlugin } from '@backstage/plugin-org';
import { SearchPage } from '@backstage/plugin-search';
import { TechRadarPage } from '@backstage/plugin-tech-radar';
import {
  TechDocsIndexPage,
  techdocsPlugin,
  TechDocsReaderPage,
} from '@backstage/plugin-techdocs';
import { TechDocsAddons } from '@backstage/plugin-techdocs-react';
import { ReportIssue } from '@backstage/plugin-techdocs-module-addons-contrib';
import { UserSettingsPage } from '@backstage/plugin-user-settings';
import { apis } from './apis';
import { entityPage } from './components/catalog/EntityPage';
import { searchPage } from './components/search/SearchPage';
import { Root } from './components/Root';

import { AlertDisplay, OAuthRequestDialog } from '@backstage/core-components';
import { createApp } from '@backstage/app-defaults';
import { AppRouter, FlatRoutes } from '@backstage/core-app-api';
import { CatalogGraphPage } from '@backstage/plugin-catalog-graph';
import { RequirePermission } from '@backstage/plugin-permission-react';
import { catalogEntityCreatePermission } from '@backstage/plugin-catalog-common/alpha';

const app = createApp({
  apis,
  bindRoutes({ bind }) {
    bind(catalogPlugin.externalRoutes, {
      createComponent: scaffolderPlugin.routes.root,
      viewTechDoc: techdocsPlugin.routes.docRoot,
    });
    bind(apiDocsPlugin.externalRoutes, {
      registerApi: catalogImportPlugin.routes.importPage,
    });
    bind(scaffolderPlugin.externalRoutes, {
      registerComponent: catalogImportPlugin.routes.importPage,
    });
    bind(orgPlugin.externalRoutes, {
      catalogIndex: catalogPlugin.routes.catalogIndex,
    });
  },
});

const routes = (
  <FlatRoutes>
    <Route path="/" element={<Navigate to="catalog" />} />
    <Route path="/catalog" element={<CatalogIndexPage />} />
    <Route
      path="/catalog/:namespace/:kind/:name"
      element={<CatalogEntityPage />}
    >
      {entityPage}
    </Route>
    <Route path="/docs" element={<TechDocsIndexPage />} />
    <Route
      path="/docs/:namespace/:kind/:name/*"
      element={<TechDocsReaderPage />}
    >
      <TechDocsAddons>
        <ReportIssue />
      </TechDocsAddons>
    </Route>
    
    <Route path="/create" element={<ScaffolderPage />} />
    <Route path="/api-docs" element={<ApiExplorerPage />} />
    <Route
      path="/tech-radar"
      element={<TechRadarPage width={1500} height={800} />}
    />
    <Route
      path="/catalog-import"
      element={
        <RequirePermission permission={catalogEntityCreatePermission}>
          <CatalogImportPage />
        </RequirePermission>
      }
    />
    <Route path="/search" element={<SearchPage />}>
      {searchPage}
    </Route>
    <Route path="/settings" element={<UserSettingsPage />} />
    <Route path="/catalog-graph" element={<CatalogGraphPage />} />
  </FlatRoutes>
);

export default app.createRoot(
  <>
    <AlertDisplay />
    <OAuthRequestDialog />
    <AppRouter>
      <Root>{routes}</Root>
    </AppRouter>
  </>,
);

**Comment by agentbellnorm** [comment]
@Remyapraveen This is an issue that has been fixed in techdocs-cli, can you get the version of the cli you're running, with `--version`?

**Comment by Remyapraveen** [comment]
Hi @agentbellnorm, I am running a techdocs-cli version 1.2.2.

**Comment by Remyapraveen** [comment]
The issue still isn't resolved, but it's an independent component and doesn't affect the techdocs access in both local and Cloud deployment.
