### ISSUE TITLE
🐛 Bug Report: Can't register components & GitHub multi-org processor stops running after backend has been up for a few days

### ISSUE THREAD

**Issue by ConnorDY** [backstage/backstage#17249]
## 📜 Description

We've noticed several issues that start occurring after our Backstage backend pod has been running for a few days (in our case it seems to happen after it's been running for about 3 or 4 days).

### **Issue 1:** Registering components stops working properly.

After the backend has been running for a few days, registering components doesn't work properly.

Specifically, we've noticed that registering a component will add the item to the `locations` database table, but it never gets added to `final_entities`.

This means the component does not show up in the catalog. Trying to register the same location again causes an error because the location already exists.

This issue occurs both when trying to register a component through the UI and when using the register scaffolder action.

### **Issue 2:** The GitHub multi-org processor stops running.

Typically this processor runs a scan on a set interval and we'll see logging output like the following:
```json
{"level":"info","message":"Reading GitHub users and teams for org: example-org","plugin":"catalog","service":"backstage","type":"plugin"}
```

After the backend pod has been running for a few days, changes to the org are no longer ingested and we no longer see any logging output like the above.

### Workaround

Our current workaround is to bounce the backend pod every 3 days, but we would prefer to not do this.

### Related Issue(s)

Possibly related to https://github.com/backstage/backstage/issues/6496.

## 👍 Expected behavior

Registering components and the GitHub multi-org processor should continue working as expected no matter how long the backend has been running.

## 👎 Actual Behavior with Screenshots

Registering components and the GitHub multi-org processor stop working after the backend has been running for several days.

### Issue 1

1. Start the Backstage backend
2. Wait for about 3-4 days
3. Try registering a component
4. Notice that the location is registered but the entity never gets created (and the component is not visible from the catalog)

### Issue 2

1. Start the Backstage backend
2. Wait for about 3-4 days
3. Notice that GitHub multi-org processor no longer works and stops producing logging output

## 🖥️ Your Environment

```
> yarn backstage-cli info
yarn run v1.22.17
$ <REDACTED>/backstage-app/node_modules/.bin/backstage-cli info
OS:   Darwin 22.3.0 - darwin/x64
node: v16.19.0
yarn: 1.22.17
cli:  0.22.0 (installed)
backstage:  1.9.1

Dependencies:
  @backstage/app-defaults                                  1.0.10, 1.1.0
  @backstage/backend-common                                0.17.0
  @backstage/backend-plugin-api                            0.2.0
  @backstage/backend-tasks                                 0.4.0
  @backstage/catalog-client                                1.2.0, 1.3.0
  @backstage/catalog-model                                 1.1.5, 1.1.4
  @backstage/cli-common                                    0.1.11
  @backstage/cli                                           0.20.0, 0.22.0
  @backstage/config-loader                                 1.1.8, 1.1.7
  @backstage/config                                        1.0.5, 1.0.6
  @backstage/core-app-api                                  1.4.0, 1.3.0
  @backstage/core-components                               0.11.2, 0.12.2, 0.12.3, 0.9.3
  @backstage/core-plugin-api                               1.2.0, 1.3.0
  @backstage/dev-utils                                     1.0.11, 1.0.10
  @backstage/errors                                        1.1.4
  @backstage/integration-aws-node                          0.1.0
  @backstage/integration-react                             1.1.9, 1.1.8
  @backstage/integration                                   1.4.1, 1.4.2
  @backstage/plugin-api-docs                               0.8.13
  @backstage/plugin-auth-backend                           0.17.2
  @backstage/plugin-auth-node                              0.2.8
  @backstage/plugin-catalog-backend-module-github          0.2.2
  @backstage/plugin-catalog-backend-module-gitlab          0.1.10
  @backstage/plugin-catalog-backend                        1.6.0
  @backstage/plugin-catalog-common                         1.0.10, 1.0.9
  @backstage/plugin-catalog-graph                          0.2.25
  @backstage/plugin-catalog-import                         0.9.3
  @backstage/plugin-catalog-node                           1.3.0
  @backstage/plugin-catalog-react                          1.2.3, 1.2.4
  @backstage/plugin-catalog                                1.7.1
  @backstage/plugin-circleci                               0.3.13
  @backstage/plugin-events-node                            0.2.0
  @backstage/plugin-github-actions                         0.5.13
  @backstage/plugin-home                                   0.4.29
  @backstage/plugin-org                                    0.6.3
  @backstage/plugin-permission-backend                     0.5.14
  @backstage/plugin-permission-common                      0.7.2, 0.7.3
  @backstage/plugin-permission-node                        0.7.2
  @backstage/plugin-permission-react                       0.4.8, 0.4.9
  @backstage/plugin-proxy-backend                          0.2.33
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.2.14
  @backstage/plugin-scaffolder-backend                     1.9.0
  @backstage/plugin-scaffolder-common                      1.2.3, 1.2.4
  @backstage/plugin-scaffolder-react                       1.0.1
  @backstage/plugin-scaffolder                             1.9.1
  @backstage/plugin-search-backend-node                    1.1.0
  @backstage/plugin-search-backend                         1.2.0
  @backstage/plugin-search-common                          1.2.0, 1.2.1
  @backstage/plugin-search-react                           1.3.1
  @backstage/plugin-search                                 1.0.6
  @backstage/plugin-sonarqube-backend                      0.1.4
  @backstage/plugin-sonarqube-react                        0.1.0
  @backstage/plugin-sonarqube                              0.6.1
  @backstage/plugin-stack-overflow                         0.1.9
  @backstage/plugin-techdocs-backend                       1.5.0
  @backstage/plugin-techdocs-node                          1.4.3
  @backstage/plugin-techdocs-react                         1.1.1
  @backstage/plugin-techdocs                               1.4.2
  @backstage/plugin-user-settings                          0.6.1
  @backstage/release-manifests                             0.0.6, 0.0.8
  @backstage/test-utils                                    1.2.4, 1.2.3
  @backstage/theme                                         0.2.16
  @backstage/types                                         1.0.2
  @backstage/version-bridge                                1.0.3
✨  Done in 1.72s.
```

## 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

See above for possibly related issues.

## 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by jhaals** [comment]
Hi! Sorry to hear that you're having issues, just to clarify are you using a processor or a provider? I see processor being mentioned but I want to double check, it's generally advised to migrate over to Entity Providers whenever possible.

It's a hard to debug as this happens so infrequent are the pod functioning normally except for new entities not showing up? Anything odd with other metrics such as cpu/memory? Speaking of metrics we do export some prometheus metics which might be helpful to debug this further if you have that infrastructure. See https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/prometheus-metrics.md

**Comment by ConnorDY** [comment]
> just to clarify are you using a processor or a provider? I see processor being mentioned but I want to double check, it's generally advised to migrate over to Entity Providers whenever possible.

We are still using a processor and not a provider. I just learned yesterday about providers. Will see if this is something we can upgrade to.

> It's a hard to debug as this happens so infrequent are the pod functioning normally except for new entities not showing up?

I believe this is accurate. We don't see any other strange behavior.

> Anything odd with other metrics such as cpu/memory? Speaking of metrics we do export some prometheus metics which might be helpful to debug this further if you have that infrastructure.

We don't have any metrics captured right now. Going to look into setting up Prometheus!

**Comment by kuangp** [comment]
> We are still using a processor and not a provider. I just learned yesterday about providers. Will see if this is something we can upgrade to.

You might be interested in the provider version of this processor I just implemented: https://github.com/backstage/backstage/pull/17285

**Comment by ConnorDY** [comment]
We have now switched over to providers where possible and are still seeing this issue where new entities are not getting created after the backend has been running for several days.

The only remaining processor we're using is the `ScaffolderEntitiesProcessor`.

Here's the code for our `catalog.ts` in case it helps:

```ts
export default async function createPlugin(
  env: PluginEnvironment,
  githubMultiOrgEntityProvider?: GithubMultiOrgEntityProvider,
) {
  const builder = await CatalogBuilder.create(env);

  builder.addEntityProvider(githubMultiOrgEntityProvider);

  builder.addProcessor(new ScaffolderEntitiesProcessor());

  builder.addLocationAnalyzers(
    new GithubLocationAnalyzer({
      discovery: env.discovery,
      config: env.config,
      tokenManager: env.tokenManager,
    }),
  );

  const { processingEngine, router } = await builder.build();

  await processingEngine.start();

  return router;
}
```

**Comment by jhaals** [comment]
Nothing that stands out in your code either, really hard to debug this :( 
Any clues in the logs?

**Comment by ConnorDY** [comment]
Sorry for the delayed response. We haven't found anything useful in our logs. Both before and after switching to providers, we don't see any sort of warnings or errors in our logs when this issue starts occurring (even with the log-level set to `debug`).

**Comment by ConnorDY** [comment]
Sorry for the delayed response. We haven't found anything useful in our logs. Both before and after switching to providers, we don't see any sort of warnings or errors in our logs when this issue starts occurring (even with the log-level set to `debug`).

The issue seems to be occurring more frequently now (after about 24 hours instead of 72 hours) as we've added more users and content to the catalog.

**Comment by camilaibs** [comment]
Hi there, is it fixed?  Could you please close the issue if that's the case 🙂 ?
