### ISSUE TITLE
🐛 Bug Report: Failure on `yarn dev`

### ISSUE THREAD

**Issue by AntoniaAdler** [backstage/backstage#22315]
### 📜 Description

Following https://backstage.io/docs/getting-started/ and running `yarn dev`, I get the following error:
`export 'useSyncExternalStore' (imported as 'React2') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
node_modules/swagger-ui-react/node_modules/react-redux/dist/react-redux.mjs`

It can be fixed by changing 
```
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
``` 
in packages/app/package.json and rerunning `yarn install`.

Did I miss anything?

### 👍 Expected behavior

The getting started tutorial should work

### 👎 Actual Behavior with Screenshots

Failure of the frontend app 

`export 'useSyncExternalStore' (imported as 'React2') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
node_modules/swagger-ui-react/node_modules/react-redux/dist/react-redux.mjs`

### 👟 Reproduction steps

following the getting started tutorial

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by AntoniaAdler** [comment]
Thanks @jamieklassen for the quick reply! Yes, the error does not show up with `npx @backstage/create-app@nightly`

**Comment by Rugvip** [comment]
Getting a patch release out so that the fix from #22297 applies to projects created today as well: https://github.com/backstage/backstage/pull/22340

This underlying issue is fixed though, so will close this issue

**Comment by flavienbwk** [comment]
Confirmed it worked.

**Comment by enryson** [comment]
i'm having the same issue right now.. i'm on 1.22.1 and i change the version of react and react-dom.. 
But this did not fix the problem.

**Comment by flavienbwk** [comment]
> i'm having the same issue right now.. i'm on 1.22.1 and i change the version of react and react-dom.. But this did not fix the problem.

FYI I've used `npx @backstage/create-app@0.5.10` to make it work.
