### ISSUE TITLE
🐛 Bug Report: Error ` TypeError: Cannot read properties of undefined (reading 'secrets')` during registeration step of GitHUB repo in BackStage UI in Dev

### ISSUE THREAD

**Issue by elamaran11** [backstage/backstage#23824]
### 📜 Description

```
[Settings](http://localhost:3000/settings)
Run of example-nodejs-template
Task ccbb5565-622c-4614-a2eb-663d8b3ead32


Search
12024-03-23T22:35:48.000Z Beginning step Fetch Base22024-03-23T22:35:48.000Z info: Fetching template content from remote URL32024-03-23T22:35:48.000Z info: Listing files and directories in template42024-03-23T22:35:48.000Z info: Processing 3 template files/directories with input values {"name":"backstage-trial"}52024-03-23T22:35:48.000Z info: Writing file catalog-info.yaml to template output path with mode 33188.62024-03-23T22:35:48.000Z info: Writing file index.js to template output path with mode 33188.72024-03-23T22:35:48.000Z info: Writing file package.json to template output path with mode 33188.82024-03-23T22:35:48.000Z info: Template result written to /var/folders/46/xp9w4wb16bb69v863xbstzqh0000gr/T/ccbb5565-622c-4614-a2eb-663d8b3ead3292024-03-23T22:35:48.000Z Finished step Fetch Base102024-03-23T22:35:48.000Z Beginning step Publish112024-03-23T22:35:49.000Z info: Init git repository {dir=/var/folders/46/xp9w4wb16bb69v863xbstzqh0000gr/T/ccbb5565-622c-4614-a2eb-663d8b3ead32}122024-03-23T22:35:49.000Z info: Adding file {dir=/var/folders/46/xp9w4wb16bb69v863xbstzqh0000gr/T/ccbb5565-622c-4614-a2eb-663d8b3ead32,filepath=.}132024-03-23T22:35:49.000Z info: Committing file to repo {dir=/var/folders/46/xp9w4wb16bb69v863xbstzqh0000gr/T/ccbb5565-622c-4614-a2eb-663d8b3ead32,message=initial commit}142024-03-23T22:35:49.000Z info: Creating new remote {dir=/var/folders/46/xp9w4wb16bb69v863xbstzqh0000gr/T/ccbb5565-622c-4614-a2eb-663d8b3ead32,remote=origin,url=https://github.com/elamaran11/backstage-trial.git}152024-03-23T22:35:49.000Z info: Pushing directory to remote {dir=/var/folders/46/xp9w4wb16bb69v863xbstzqh0000gr/T/ccbb5565-622c-4614-a2eb-663d8b3ead32,remote=origin}162024-03-23T22:35:50.000Z warn: Branch protection was not enabled as it requires GitHub Pro for private repositories172024-03-23T22:35:50.000Z Finished step Publish182024-03-23T22:35:50.000Z Beginning step Register192024-03-23T22:35:50.000Z info: Registering https://github.com/elamaran11/backstage-trial/tree/master/catalog-info.yaml in the catalog202024-03-23T22:35:50.000Z TypeError: Cannot read properties of undefined (reading 'secrets')2[1](http://localhost:3000/create/tasks/ccbb5565-622c-4614-a2eb-663d8b3ead32#line-1)    at Object.getInitiatorCredentials (/Users/elamaras/WorkDocsDownloads/AWS_Internal/Containers/mlops_demos/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/StorageTaskBroker.ts:18[2](http://localhost:3000/create/tasks/ccbb5565-622c-4614-a2eb-663d8b3ead32#line-2):19)22    at Object.handler (/Users/elamaras/WorkDocsDownloads/AWS_Internal/Containers/mlops_demos/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/actions/builtin/catalog/register.ts:1[3](http://localhost:3000/create/tasks/ccbb5565-622c-4614-a2eb-663d8b3ead32#line-3)1:31)23    at NunjucksWorkflowRunner.executeStep (/Users/elamaras/WorkDocsDownloads/AWS_Internal/Containers/mlops_demos/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:37[4](http://localhost:3000/create/tasks/ccbb5565-622c-4614-a2eb-663d8b3ead32#line-4):22)24    at NunjucksWorkflowRunner.execute (/Users/elamaras/WorkDocsDownloads/AWS_Internal/Containers/mlops_demos/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:[5](http://localhost:3000/create/tasks/ccbb5565-622c-4614-a2eb-663d8b3ead32#line-5)01:9)25    at TaskWorker.runOneTask (/Users/elamaras/WorkDocsDownloads/AWS_Internal/Containers/mlops_demos/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:17[6](http://localhost:3000/create/tasks/ccbb5565-622c-4614-a2eb-663d8b3ead32#line-6):26)26    at async run (/Users/elamaras/WorkDocsDownloads/AWS_Internal/Containers/mlops_demos/backstage/node_modules/p-queue/dist/index.js:163:2[9](http://localhost:3000/create/tasks/ccbb5565-622c-4614-a2eb-663d8b3ead32#line-9))
```

### 👍 Expected behavior

Registeration step should work fine

### 👎 Actual Behavior with Screenshots

```
[Settings](http://localhost:3000/settings)
Run of example-nodejs-template
Task ccbb5565-622c-4614-a2eb-663d8b3ead32


Search
12024-03-23T22:35:48.000Z Beginning step Fetch Base22024-03-23T22:35:48.000Z info: Fetching template content from remote URL32024-03-23T22:35:48.000Z info: Listing files and directories in template42024-03-23T22:35:48.000Z info: Processing 3 template files/directories with input values {"name":"backstage-trial"}52024-03-23T22:35:48.000Z info: Writing file catalog-info.yaml to template output path with mode 33188.62024-03-23T22:35:48.000Z info: Writing file index.js to template output path with mode 33188.72024-03-23T22:35:48.000Z info: Writing file package.json to template output path with mode 33188.82024-03-23T22:35:48.000Z info: Template result written to /var/folders/46/xp9w4wb16bb69v863xbstzqh0000gr/T/ccbb5565-622c-4614-a2eb-663d8b3ead3292024-03-23T22:35:48.000Z Finished step Fetch Base102024-03-23T22:35:48.000Z Beginning step Publish112024-03-23T22:35:49.000Z info: Init git repository {dir=/var/folders/46/xp9w4wb16bb69v863xbstzqh0000gr/T/ccbb5565-622c-4614-a2eb-663d8b3ead32}122024-03-23T22:35:49.000Z info: Adding file {dir=/var/folders/46/xp9w4wb16bb69v863xbstzqh0000gr/T/ccbb5565-622c-4614-a2eb-663d8b3ead32,filepath=.}132024-03-23T22:35:49.000Z info: Committing file to repo {dir=/var/folders/46/xp9w4wb16bb69v863xbstzqh0000gr/T/ccbb5565-622c-4614-a2eb-663d8b3ead32,message=initial commit}142024-03-23T22:35:49.000Z info: Creating new remote {dir=/var/folders/46/xp9w4wb16bb69v863xbstzqh0000gr/T/ccbb5565-622c-4614-a2eb-663d8b3ead32,remote=origin,url=https://github.com/elamaran11/backstage-trial.git}152024-03-23T22:35:49.000Z info: Pushing directory to remote {dir=/var/folders/46/xp9w4wb16bb69v863xbstzqh0000gr/T/ccbb5565-622c-4614-a2eb-663d8b3ead32,remote=origin}162024-03-23T22:35:50.000Z warn: Branch protection was not enabled as it requires GitHub Pro for private repositories172024-03-23T22:35:50.000Z Finished step Publish182024-03-23T22:35:50.000Z Beginning step Register192024-03-23T22:35:50.000Z info: Registering https://github.com/elamaran11/backstage-trial/tree/master/catalog-info.yaml in the catalog202024-03-23T22:35:50.000Z TypeError: Cannot read properties of undefined (reading 'secrets')2[1](http://localhost:3000/create/tasks/ccbb5565-622c-4614-a2eb-663d8b3ead32#line-1)    at Object.getInitiatorCredentials (/Users/elamaras/WorkDocsDownloads/AWS_Internal/Containers/mlops_demos/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/StorageTaskBroker.ts:18[2](http://localhost:3000/create/tasks/ccbb5565-622c-4614-a2eb-663d8b3ead32#line-2):19)22    at Object.handler (/Users/elamaras/WorkDocsDownloads/AWS_Internal/Containers/mlops_demos/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/actions/builtin/catalog/register.ts:1[3](http://localhost:3000/create/tasks/ccbb5565-622c-4614-a2eb-663d8b3ead32#line-3)1:31)23    at NunjucksWorkflowRunner.executeStep (/Users/elamaras/WorkDocsDownloads/AWS_Internal/Containers/mlops_demos/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:37[4](http://localhost:3000/create/tasks/ccbb5565-622c-4614-a2eb-663d8b3ead32#line-4):22)24    at NunjucksWorkflowRunner.execute (/Users/elamaras/WorkDocsDownloads/AWS_Internal/Containers/mlops_demos/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:[5](http://localhost:3000/create/tasks/ccbb5565-622c-4614-a2eb-663d8b3ead32#line-5)01:9)25    at TaskWorker.runOneTask (/Users/elamaras/WorkDocsDownloads/AWS_Internal/Containers/mlops_demos/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:17[6](http://localhost:3000/create/tasks/ccbb5565-622c-4614-a2eb-663d8b3ead32#line-6):26)26    at async run (/Users/elamaras/WorkDocsDownloads/AWS_Internal/Containers/mlops_demos/backstage/node_modules/p-queue/dist/index.js:163:2[9](http://localhost:3000/create/tasks/ccbb5565-622c-4614-a2eb-663d8b3ead32#line-9))
```

### 👟 Reproduction steps

Use the latest version and run `yarn dev` for integration with GitHUb

### 📃 Provide the context for the Bug.

Error while registering step of GitHUB repo in BackStage UI in Dev

### 🖥️ Your Environment

Mac

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by elamaran11** [comment]
![Cursor_and_Run_of_example-nodejs-template___Scaffolded_Backstage_App](https://github.com/backstage/backstage/assets/51791117/90836f2a-9a22-4539-a2da-72cad9b8373e)

**Comment by SeanoNET** [comment]
Downgrading package `@backstage/plugin-scaffolder-backend` resolved this while we wait for a fix

`yarn --cwd packages/backend add @backstage/plugin-scaffolder-backend@1.21.0 `

**Comment by elamaran11** [comment]
That Worked, thankyou!

**Comment by waldi** [comment]
@elamaran11  Why was this closed? Don't we need a fix for this?

**Comment by elamaran11** [comment]
Reopening this for the fix but downgrading worked for me!

**Comment by tudi2d** [comment]
Did you try it with the `1.25` mainline release & scaffolder-backend `1.22.3` before reopening the issue? I believe this might have been addressed by: `Fixed an issue causing actions to fail when retrieving auth credentials`

**Comment by benjdlambert** [comment]
Closing as this should be fixed in `1.25.0`, please reach out if you're still having problems :tada:

**Comment by zkdan** [comment]
I'm still having problems! 

The same issue as #23820,  `Template action with ID 'publish:github' is not registered.` when I try to create a component from the Node template.

I tried [adding the github module](https://github.com/backstage/backstage/issues/23820#issuecomment-2016523278) and [downgrading](https://github.com/backstage/backstage/issues/23824#issuecomment-2016647401). I just deleted everything and restarted the backstage tutorial today so I think I'm using the latest.

**Comment by benjdlambert** [comment]
@zkdan there's help for your issue in original issue. You need to install the modules and `backend.add` them to wire them together.

https://github.com/backstage/backstage/issues/23820#issuecomment-2022424135

**Comment by zkdan** [comment]
So fast! Thank you! I added the `@backstage/plugin-scaffolder-backend-module-github` and now have a new, unrelated problem. 🎉

**Comment by theopskart22** [comment]
same issue I am getting.
NotFoundError: Template action with ID 'publish:github' is not registered.

**Comment by benjdlambert** [comment]
@theopskart22 do you have the line `backend.add(import('@backstage/plugin-scaffolder-backend-module-github'))` in your `packages/backend/src/index.ts`?
