### ISSUE TITLE
🐛 Bug Report: New scalable events service depends on events-backend being up first

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#27207]
### 📜 Description

Under the new implementation for the scalable `EventsService`, calling `subscribe` depends on the events-backend plugin being up and running to receive the API request - there a few event modules (eg. [eventsModuleGithubEventRouter](https://github.com/backstage/backstage/blob/master/plugins/events-backend-module-github/src/service/eventsModuleGithubEventRouter.ts), [eventsModuleGitlabEventRouter](https://github.com/backstage/backstage/blob/master/plugins/events-backend-module-gitlab/src/service/eventsModuleGitlabEventRouter.ts), etc) that broke since modules are initialized before their corresponding plugin and so the `subscribe()` calls in those modules fail with a "503 service unavailable" since the events-backend has not started up yet. 

A simple fix for those modules is to wrap the calls in a `lifecycle.addStartupHook` however this brings about a boarder issue of how other plugins that interact with the `EventsService` also now have an indirect dependency of having the events-backend be initialized first. 

For example we have catalog providers that are hooked up to events and our catalog backend startup fails when hitting the [`subscribe` calls](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts#L243) if the events-backend is not up yet. There's probably a few more places in this repo where we not handling the `subscribe` call failing correctly but I'm not sure if the solution here is to ensure we have proper error handling everywhere we call `subscribe` - some of which is part of startup code so not sure if there should also be a retry mechanism since we don't know if either the events backend is simply down or not yet fully started.

### 👍 Expected behavior

See description

### 👎 Actual Behavior with Screenshots

See description

### 👟 Reproduction steps

Install the events-backend with one of the events modules that hooks up a sub topic router such as https://github.com/backstage/backstage/blob/master/plugins/events-backend-module-github/src/service/eventsModuleGithubEventRouter.ts - when starting up the backend the module will fail to initialize with a 503 on the subscribe call

### 🖥️ Your Environment

Backstage v1.32.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kuangp** [comment]
wanted to open this issue first to discuss the problem before putting up fixes for the broken modules in question since not sure if the appropriate fix is to address it everywhere we're currently calling `subscribe` as part of startup code or if a wider fix to the `EventsService` is more pragmatic since the order of init limitation makes the API a bit messy now 

cc: @Rugvip to get your thoughts when you get a chance 🙏

**Comment by Rugvip** [comment]
@kuangp ah yep thank you, this is gonna be an issue indeed! 👍 

Given the behavior of the subscribe function I think it makes sense to retry. It's actually already part of the polling to try to upsert subscriptions if they don't exist, just not the initial request: https://github.com/backstage/backstage/blob/232a9600f07d40e5a55b1f5eb8cb85500ea6ec07/plugins/events-node/src/api/DefaultEventsService.ts#L211-L228

I think the best fix here might be to simply skip the initial subscription creation and leave it to the polling. Just gotta take care to keep the 404 behavior to handle the case where the events backend isn't present: https://github.com/backstage/backstage/blob/232a9600f07d40e5a55b1f5eb8cb85500ea6ec07/plugins/events-node/src/api/DefaultEventsService.ts#L175-L181

**Comment by Silthus** [comment]
I ran into this error after upgrading to the latest Backstage release. Is there a workaround I can use, or do I need to downgrade?

**Comment by polarp** [comment]
Hey guys, just wanted to loop in the conv and say that we're also experiencing the same issue when tried to upgrade from 1.27.7 to 1.32.0.

**Comment by Rugvip** [comment]
Fix is on the way in #27227

**Comment by kunickiaj** [comment]
I'm sure this will be out quickly, but is there a workaround in the meantime? I am seeing this on 1.31.3 I believe.

**Comment by Ginger0913** [comment]
I am still seeing this issue on 1.32.1
Not sure if it was required, but I also set up `useEventBus: auto` in my app-config.yaml under `events`

**Comment by kunickiaj** [comment]
It’s fixed in 1.32.2

**Comment by LegendSebastianoL** [comment]
🤔 I can still see this error in the latest version of Backstage.

```
[backend]: 2024-11-27T09:11:44.810Z catalog warn Event subscribe request failed with status 404, events backend not found. Will only receive events that were sent locally on this process.
```

**Comment by tommy04062019** [comment]
> It’s fixed in 1.32.2
> […](#)

@kunickiaj : Still appear in 1.38.0

**Comment by AlanWaiteDSG** [comment]
Still appears in 1.39.0
