### ISSUE TITLE
🐛 Bug Report: lint broken after `yarn backstage-cli versions:bump`

### ISSUE THREAD

**Issue by danielfigueiredo** [backstage/backstage#27500]
### 📜 Description

Hey team, I was performing another regular Backstage versions:bump task using the CLI and noticed a conflicting lint configuration.

The CLI version with the issue is `^0.28.2` - even the `v.next.2` has this bug.

It happens because the [current upstream configuration](https://github.com/backstage/backstage/blob/master/packages/cli/package.json#L80-L81) uses: 
```json
    "@typescript-eslint/eslint-plugin": "^6.12.0",
    "@typescript-eslint/parser": "^6.7.2",
```
But [all the plugins](https://github.com/backstage/backstage/blob/master/packages/cli/package.json#L95-L105) are using `eslint` v8.6.

The quick fix for anyone with this issue is to upgrade both dependencies to v7, e.g.:
```json
    "@typescript-eslint/eslint-plugin": "^7.18.0",
    "@typescript-eslint/parser": "^7.18.0",
```

Ideally they are all bumped to v8, but the v8 upgrade has more breaking changes I didn't have time to go through.

### 👍 Expected behavior

Running `backstage-cli repo lint` always works if not customizations are provided over the upstream configuration.

### 👎 Actual Behavior with Screenshots

```sh
$ backstage-cli repo lint

TypeError: Failed to load plugin 'jest' declared in '.eslintrc.js': Class extends value undefined is not a constructor or null
Referenced from: /Users/dfigueiredo/code/ws/backstage/plugins/deployments-backend/.eslintrc.js

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### 👟 Reproduction steps

1. Run `yarn backstage-cli versions:bump`
2. Confirm CLI version is updated to `0.28.2` or greater by running `yarn why @backstage/cli`
3. `yarn backstage-cli repo lint`

### 🖥️ Your Environment

yarn run v1.22.22
$ /Users/dfigueiredo/code/ws/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 23.5.0 - darwin/arm64
node: v18.20.4
yarn: 1.22.22
cli:  0.28.2 (installed)
backstage:  1.32.5

Dependencies:
  @backstage/app-defaults                                          1.5.12
  @backstage/backend-app-api                                       0.8.0, 0.9.3, 1.0.1
  @backstage/backend-common                                        0.23.3, 0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.4.4, 0.5.2
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.18, 0.2.0
  @backstage/backend-plugin-api                                    0.7.0, 0.8.1, 1.0.0, 1.0.1
  @backstage/backend-tasks                                         0.5.27, 0.6.1
  @backstage/backend-test-utils                                    0.4.4, 1.0.2
  @backstage/catalog-client                                        1.7.0, 1.7.1
  @backstage/catalog-model                                         1.7.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.8, 0.2.9
  @backstage/cli                                                   0.28.2
  @backstage/config-loader                                         1.9.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.15.1
  @backstage/core-compat-api                                       0.2.8, 0.3.1
  @backstage/core-components                                       0.14.10, 0.15.1
  @backstage/core-plugin-api                                       1.10.0, 1.9.3
  @backstage/dev-utils                                             1.1.2
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.0
  @backstage/frontend-defaults                                     0.1.1
  @backstage/frontend-plugin-api                                   0.6.7, 0.7.0, 0.9.0
  @backstage/frontend-test-utils                                   0.2.1
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.30, 1.2.0
  @backstage/integration                                           1.15.0, 1.15.1
  @backstage/plugin-api-docs                                       0.11.11
  @backstage/plugin-app-backend                                    0.3.76
  @backstage/plugin-app-node                                       0.1.26
  @backstage/plugin-app                                            0.1.1
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.1
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.1
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.2.1
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.1
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.1
  @backstage/plugin-auth-backend-module-github-provider            0.2.1
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.1
  @backstage/plugin-auth-backend-module-google-provider            0.2.1
  @backstage/plugin-auth-backend-module-guest-provider             0.2.1
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.1
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.1
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.1
  @backstage/plugin-auth-backend-module-okta-provider              0.1.1
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.1
  @backstage/plugin-auth-backend                                   0.23.1
  @backstage/plugin-auth-node                                      0.4.17, 0.5.2, 0.5.3
  @backstage/plugin-auth-react                                     0.1.7
  @backstage/plugin-bitbucket-cloud-common                         0.2.24
  @backstage/plugin-catalog-backend-module-github-org              0.3.3
  @backstage/plugin-catalog-backend-module-github                  0.7.6
  @backstage/plugin-catalog-backend-module-logs                    0.1.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.1
  @backstage/plugin-catalog-backend-module-unprocessed             0.5.1
  @backstage/plugin-catalog-backend                                1.27.1
  @backstage/plugin-catalog-common                                 1.1.0
  @backstage/plugin-catalog-graph                                  0.4.11
  @backstage/plugin-catalog-import                                 0.12.5
  @backstage/plugin-catalog-node                                   1.13.0, 1.13.1
  @backstage/plugin-catalog-react                                  1.12.3, 1.14.0
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.4
  @backstage/plugin-catalog-unprocessed-entities                   0.2.9
  @backstage/plugin-catalog                                        1.24.0
  @backstage/plugin-devtools-backend                               0.4.1
  @backstage/plugin-devtools-common                                0.1.12
  @backstage/plugin-devtools                                       0.1.19
  @backstage/plugin-events-backend-module-aws-sqs                  0.4.4
  @backstage/plugin-events-backend-module-github                   0.2.13
  @backstage/plugin-events-backend                                 0.3.15
  @backstage/plugin-events-node                                    0.3.10, 0.4.4
  @backstage/plugin-home-react                                     0.1.16, 0.1.18
  @backstage/plugin-home                                           0.8.0
  @backstage/plugin-kubernetes-backend                             0.18.7
  @backstage/plugin-kubernetes-common                              0.8.3
  @backstage/plugin-kubernetes-node                                0.1.20
  @backstage/plugin-notifications-backend                          0.4.2
  @backstage/plugin-notifications-common                           0.0.5
  @backstage/plugin-notifications-node                             0.2.8
  @backstage/plugin-notifications                                  0.3.2
  @backstage/plugin-org                                            0.6.31
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.1
  @backstage/plugin-permission-backend                             0.5.50
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.3, 0.8.4
  @backstage/plugin-permission-react                               0.4.25, 0.4.27
  @backstage/plugin-proxy-backend                                  0.5.7
  @backstage/plugin-scaffolder-backend-module-azure                0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.1
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.1
  @backstage/plugin-scaffolder-backend-module-github               0.5.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.6.0
  @backstage/plugin-scaffolder-backend-module-rails                0.5.1
  @backstage/plugin-scaffolder-backend                             1.26.2
  @backstage/plugin-scaffolder-common                              1.5.6
  @backstage/plugin-scaffolder-node-test-utils                     0.1.14
  @backstage/plugin-scaffolder-node                                0.5.0
  @backstage/plugin-scaffolder-react                               1.13.2
  @backstage/plugin-scaffolder                                     1.26.2
  @backstage/plugin-search-backend-module-catalog                  0.2.4
  @backstage/plugin-search-backend-module-elasticsearch            1.6.1
  @backstage/plugin-search-backend-module-explore                  0.2.4
  @backstage/plugin-search-backend-module-pg                       0.5.37
  @backstage/plugin-search-backend-module-techdocs                 0.3.1
  @backstage/plugin-search-backend-node                            1.3.4
  @backstage/plugin-search-backend                                 1.6.1
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.7.14, 1.8.1
  @backstage/plugin-search                                         1.4.18
  @backstage/plugin-signals-backend                                0.2.2
  @backstage/plugin-signals-node                                   0.1.13
  @backstage/plugin-signals-react                                  0.0.6
  @backstage/plugin-signals                                        0.0.11
  @backstage/plugin-techdocs-backend                               1.11.1
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.16
  @backstage/plugin-techdocs-node                                  1.12.12, 1.12.11
  @backstage/plugin-techdocs-react                                 1.2.9
  @backstage/plugin-techdocs                                       1.11.0
  @backstage/plugin-user-settings-backend                          0.2.26
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.14
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.7.0
  @backstage/theme                                                 0.5.6, 0.6.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.10, 1.0.8
Done in 0.94s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @danielfigueiredo, we run this command as part of the Demo site PR/CI build and don't have any issues - https://github.com/backstage/demo/actions/workflows/pull.yml

I'll note that in the the environment details you shared there are a lot of duplicate versions which have caused issues in the past, this may not be the case here but worth cleaning up. If you are using Yarn 4 then you can run `yarn dedupe` if you are using Yarn 1 (Classic) you can use the [yarn-deduplicate](https://www.npmjs.com/package/yarn-deduplicate) package.

**Comment by danielfigueiredo** [comment]
We've been using `yarn-deduplicate` for a few years, we are still locked in yarn v1 though. I fixed this essentially by adding a resolution to the versions described above (v7) and then it just works.
I literally commented out all of our lint configs so it is extending upstream directly and same error originating from the CLI package.
Several reports of similar issues with the jest plugin amongst other, points back to these two libraries not being up to date with eslintl:
* https://github.com/jest-community/eslint-plugin-jest/issues/966
* https://github.com/eslint/eslint/issues/15149

We've been maintaining our backstage for a few years now, it is strange that only us using yarn deduplicate would be facing these issues only when updating to this specific cli version, and on top of that the resolution we added to package.json is for a dependency the CLI brings in, not us. None of these dependencies are managed by us (or explicitly added in any package.json across the monorepo).

**Comment by awanlin** [comment]
Yeah, I'm just trying to understand better why you are having this issue as I would think this would be a common problem based on what you initially shared. I just tried this in a Yarn 1 test environment I have and it also works, sadly I can't share this as it's internal.

As for the PR, we'd probably want to do that eventually anyway so it makes sense, I'll leave the review of it to the maintainers.  

Regarding the deduplication I'm not convinced that the issue here is caused by duplicates but based on what you shared I don't think it's working for you. For example: `@backstage/backend-common 0.23.3, 0.24.1, 0.25.0`. There's three versions of `@backstage/backend-common`, this has been know to cause issues, and I would only expect to see one version here.

**Comment by vanessap-aa** [comment]
Hey! We ran into this same issue when trying to upgrade our standalone plugin. Still trying to debug. We attempted to set the resolution to those packages but that did not solve our problem.

**Comment by jar145** [comment]
I'm encountering this same issue after updating backstage to `1.36.1`.

**Comment by anicke** [comment]
I had to "force" an upgrade of eslint. Probably not the correct way but I added this to the "package.json", then "yarn install". 

```json
  "resolutions": {
    "eslint": "8.57.0"
  },
```
If linting works now you can remove the "eslint" entry from the "resolutions", it should still resolve to something "recent".

**Comment by jar145** [comment]
That worked perfectly @anicke, and was able to remove it afterwards. Thank you!
