### ISSUE TITLE
Failed to load entity kinds - could not fetch 

### ISSUE THREAD

**Issue by eliassal** [backstage/backstage#28381]
### 📜 Description

 have a fresh new VM ubuntu 24.04, followed all instructions at https://backstage.io/docs/getting-started/, when I ran
npx @backstage/create-app@latest, 
everything goes fine, the I run yarn dev, firefox starts, I get a message 
![image](https://github.com/user-attachments/assets/a89ae8c1-68d1-4b5b-a813-c280e5ee36ae)

I hit enter, I get into the web site but always getting the error
![image](https://github.com/user-attachments/assets/8f29af94-60b6-47e6-9aad-8a2018fb4715)

reading some threads here, I change port 7007, it did not help. using machine name instead of localhost or 127.0.0.1 but nothing helps

Thanks for your help

### 👍 Expected behavior

works as indicated in the getting started

### 👎 Actual Behavior with Screenshots

provided above

### 👟 Reproduction steps

1. npx @backstage/create-app@latest, 
2. yarn dev

### 📃 Provide the context for the Bug.

Default

### 🖥️ Your Environment

Ubuntu 24 VM, when I run
yarn backstage-cli info
I get

OS:   Linux 6.8.0-49-generic - linux/x64
node: v22.11.0
yarn: 4.4.1
cli:  0.29.4 (installed)
backstage:  1.34.0

Dependencies:
  @backstage/app-defaults                                          1.5.15
  @backstage/backend-app-api                                       1.1.0
  @backstage/backend-common                                        0.25.0
  @backstage/backend-defaults                                      0.6.2
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.4.0
  @backstage/backend-plugin-api                                    1.1.0
  @backstage/catalog-client                                        1.9.0
  @backstage/catalog-model                                         1.7.2
  @backstage/cli-common                                            0.1.15
  @backstage/cli-node                                              0.2.11
  @backstage/cli                                                   0.29.4
  @backstage/config-loader                                         1.9.4
  @backstage/config                                                1.3.1
  @backstage/core-app-api                                          1.15.3
  @backstage/core-compat-api                                       0.3.4
  @backstage/core-components                                       0.16.2
  @backstage/core-plugin-api                                       1.10.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.6
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.3
  @backstage/frontend-defaults                                     0.1.4
  @backstage/frontend-plugin-api                                   0.9.3
  @backstage/frontend-test-utils                                   0.2.4
  @backstage/integration-aws-node                                  0.1.14
  @backstage/integration-react                                     1.2.2
  @backstage/integration                                           1.16.0
  @backstage/plugin-api-docs                                       0.12.2
  @backstage/plugin-app-backend                                    0.4.3
  @backstage/plugin-app-node                                       0.1.28
  @backstage/plugin-app                                            0.1.4
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.3
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.3
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.3.1
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.3
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.3
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.3
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.3
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.3
  @backstage/plugin-auth-backend-module-github-provider            0.2.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.3
  @backstage/plugin-auth-backend-module-google-provider            0.2.3
  @backstage/plugin-auth-backend-module-guest-provider             0.2.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.3
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.3
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.3
  @backstage/plugin-auth-backend-module-okta-provider              0.1.3
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.3
  @backstage/plugin-auth-backend                                   0.24.1
  @backstage/plugin-auth-node                                      0.5.5
  @backstage/plugin-auth-react                                     0.1.10
  @backstage/plugin-bitbucket-cloud-common                         0.2.26
  @backstage/plugin-catalog-backend-module-logs                    0.1.5
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.3
  @backstage/plugin-catalog-backend                                1.29.0
  @backstage/plugin-catalog-common                                 1.1.2
  @backstage/plugin-catalog-graph                                  0.4.14
  @backstage/plugin-catalog-import                                 0.12.8
  @backstage/plugin-catalog-node                                   1.15.0
  @backstage/plugin-catalog-react                                  1.15.0
  @backstage/plugin-catalog                                        1.26.0
  @backstage/plugin-events-node                                    0.4.6
  @backstage/plugin-kubernetes-backend                             0.19.1
  @backstage/plugin-kubernetes-common                              0.9.1
  @backstage/plugin-kubernetes-node                                0.2.1
  @backstage/plugin-kubernetes-react                               0.5.2
  @backstage/plugin-kubernetes                                     0.12.2
  @backstage/plugin-org                                            0.6.34
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.3
  @backstage/plugin-permission-backend                             0.5.52
  @backstage/plugin-permission-common                              0.8.3
  @backstage/plugin-permission-node                                0.8.6
  @backstage/plugin-permission-react                               0.4.29
  @backstage/plugin-proxy-backend                                  0.5.9
  @backstage/plugin-scaffolder-backend-module-azure                0.2.4
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.4
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.4
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.5
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.4
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.4
  @backstage/plugin-scaffolder-backend-module-github               0.5.4
  @backstage/plugin-scaffolder-backend-module-gitlab               0.7.0
  @backstage/plugin-scaffolder-backend                             1.28.0
  @backstage/plugin-scaffolder-common                              1.5.8
  @backstage/plugin-scaffolder-node                                0.6.2
  @backstage/plugin-scaffolder-react                               1.14.2
  @backstage/plugin-scaffolder                                     1.27.3
  @backstage/plugin-search-backend-module-catalog                  0.2.6
  @backstage/plugin-search-backend-module-pg                       0.5.39
  @backstage/plugin-search-backend-module-techdocs                 0.3.4
  @backstage/plugin-search-backend-node                            1.3.6
  @backstage/plugin-search-backend                                 1.8.0
  @backstage/plugin-search-common                                  1.2.16
  @backstage/plugin-search-react                                   1.8.4
  @backstage/plugin-search                                         1.4.21
  @backstage/plugin-signals-react                                  0.0.8
  @backstage/plugin-techdocs-backend                               1.11.4
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.19
  @backstage/plugin-techdocs-node                                  1.12.15
  @backstage/plugin-techdocs-react                                 1.2.12
  @backstage/plugin-techdocs                                       1.12.0
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.17
  @backstage/release-manifests                                     0.0.12
  @backstage/test-utils                                            1.7.3
  @backstage/theme                                                 0.6.3
  @backstage/types                                                 1.2.0
  @backstage/version-bridge                                        1.0.10

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
I see `bkstage-ansible:3000` as url in your screenshot. Have you changed anything in app-config? Does it work if you use the default app-config?

**Comment by eliassal** [comment]
Hi, yes @vinzscam, I tried everythiong, default, 127.0.0.1, then I ended using machine name, I also tried changing 7007 port by 7008 and 80 getting the exact same error

**Comment by eliassal** [comment]
Also, I tried with node 20 as well as 22, same thing

**Comment by eliassal** [comment]
Also, what is strange, I have created an app 1 month ago with node 20, I rerun yarn dev in its folder and did not get the error:
![image](https://github.com/user-attachments/assets/8a1de79c-0396-411b-a9a6-c7d105b4cb22)

Does this mean that 1st application blocks ports?
As I said for the application that is erroring, I cahnged ports 3000 to 3008 and 7007 to 7008 which did not help

**Comment by Rugvip** [comment]
Backend logs are logged to the terminal where you ran `yarn dev`, they're the ones prefixed with `[backend]:`

**Comment by eliassal** [comment]
Hi @Rugvip please see the snapshot, getting the error but there is no log in the terminal

![image](https://github.com/user-attachments/assets/c92b5f9f-85b7-4461-81ad-1db524e53846)

**Comment by eliassal** [comment]
@vinzscam , yes I use the VM machine bkstage-ansible instead of localhost in order to be able to reach it from my desktop which is not the case, I am getting connection refused. Firewall is disabledbut still cant connect to vm with port 3000. Is there a config to allow remote access from other machines?

**Comment by eliassal** [comment]
Hi, any ideas to fix those issues? Thanks

**Comment by Rugvip** [comment]
@eliassal ah! that's gonna be the issue that's solved by https://github.com/backstage/backstage/pull/28296, could you try the solution from that PR?

**Comment by eliassal** [comment]
Yes @Rugvip I used -j 2 and it went through, however, I still get the following alert
![image](https://github.com/user-attachments/assets/ac0b5079-e2d6-4899-8b26-f7f66312f0e7)

I click on OK and enter as guest. Why it goes to legacy logging?
Can you please tell me how can have my login as admin?

**Comment by Rugvip** [comment]
@eliassal you can press "ok", it had switched to a different auth mode for dev due to not being able to reach the backend
