### ISSUE TITLE
🐛 Bug Report: Error after emptying an array element

### ISSUE THREAD

**Issue by Alex-C-github** [backstage/backstage#28676]
### 📜 Description

Consider a simple 2-step form, the first step can contain whatever field, the second contains an array containing a string field.
When filling the field nested in the 2nd step array, emptying it right after, going back to the 1st step and going to the 2nd step again, this error will be raised : "**Cannot use 'in' operator to search for 'ui:field' in undefined**"

### 👍 Expected behavior

No error should be raised.

### 👎 Actual Behavior with Screenshots

> Video : https://github.com/user-attachments/assets/4ed83407-f182-439b-b7be-2146844e1219

This error was raised:

**TypeError**
Cannot use 'in' operator to search for 'ui:field' in undefined

**Call Stack**
 doValidate
  node_modules/@backstage/plugin-scaffolder/node_modules/@backstage/plugin-scaffolder-react/dist/next/components/Stepper/createAsyncValidators.esm.js:60:24
 validate
  node_modules/@backstage/plugin-scaffolder/node_modules/@backstage/plugin-scaffolder-react/dist/next/components/Stepper/createAsyncValidators.esm.js:72:17
 eval
  node_modules/@backstage/plugin-scaffolder/node_modules/@backstage/plugin-scaffolder-react/dist/next/components/Stepper/createAsyncValidators.esm.js:99:18
 eval
  node_modules/@backstage/plugin-scaffolder/node_modules/@backstage/plugin-scaffolder-react/dist/next/components/Stepper/Stepper.esm.js:139:40
 Form.eval
  node_modules/@backstage/plugin-scaffolder/node_modules/@rjsf/core/lib/components/Form.js:245:25
 callCallback
  node_modules/react-dom/cjs/react-dom.development.js:15036:12
 commitUpdateQueue
  node_modules/react-dom/cjs/react-dom.development.js:15057:9
 commitLayoutEffectOnFiber
  node_modules/react-dom/cjs/react-dom.development.js:23398:13
 commitLayoutMountEffects_complete
  node_modules/react-dom/cjs/react-dom.development.js:24722:9
 commitLayoutEffects_begin
  node_modules/react-dom/cjs/react-dom.development.js:24708:7

### 👟 Reproduction steps

1. Create the template to reproduce the bug
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: bug-demo
  title: Bug Demonstration Template
  description: A template to demonstrate a bug with two parameter steps
spec:
  owner: user:guest
  type: resource
  parameters:
    - title: Step 1
      properties:
        step1Field:
          title: Step 1 Field
          type: string
          description: This is a field for step 1
        
    - title: Step 2
      properties:
        step2Array:
          title: Step 2 Array
          type: array
          items:
            type: object
            properties:
              step2Field:
                title: Step 2 Field
                type: string
                description: This is a field for step 2
  steps:
    - id: step1
      name: Step 1
      action: debug:log
      input:
        message: 'Step 1 Field: ${{ parameters.step1Field }}'
    - id: step2
      name: Step 2
      action: debug:log
      input:
        message: 'Step 2 Field: ${{ parameters.step2Field }}'
```
2. Go to the form and fill in step1Field
3. Fill in step2Field
4. Empty step2Field
5. Go back to the form's 1st step
6. Go again to the form's 2nd step

### 📃 Provide the context for the Bug.

I randomly discovered this bug while making a demo. I had to refresh the page and fill in the form again.

### 🖥️ Your Environment

# Browser
|             |                    |
|---------|-------------|
|Arc         | 132.0.6834.111 (Official build) (64 bits)|
|Revision | c252d6a429e2ccfd21d062e643983b145e8bf0a7-refs/branch-heads/6834_101@{#4}|
|JavaScript | V8 13.2.1010152|
|User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36|

# Backstage config

OS:   Linux 5.15.167.4-microsoft-standard-WSL2 - linux/x64
node: v22.11.0
yarn: 4.6.0
cli:  0.29.5 (installed)
backstage:  1.35.0

Dependencies:
  @backstage/app-defaults                                          1.5.16
  @backstage/backend-app-api                                       1.1.1
  @backstage/backend-common                                        0.25.0
  @backstage/backend-defaults                                      0.7.0
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.4.1
  @backstage/backend-plugin-api                                    1.0.2, 1.1.1
  @backstage/backend-test-utils                                    1.2.1
  @backstage/catalog-client                                        1.8.0, 1.9.0, 1.9.1
  @backstage/catalog-model                                         1.7.1, 1.7.2, 1.7.3
  @backstage/cli-common                                            0.1.15
  @backstage/cli-node                                              0.2.12
  @backstage/cli                                                   0.29.5
  @backstage/config-loader                                         1.9.2, 1.9.5
  @backstage/config                                                1.3.0, 1.3.1, 1.3.2
  @backstage/core-app-api                                          1.15.4, 1.15.3
  @backstage/core-compat-api                                       0.3.4, 0.3.5
  @backstage/core-components                                       0.14.10, 0.16.2, 0.16.3
  @backstage/core-plugin-api                                       1.10.3, 1.10.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.5, 1.2.6, 1.2.7
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.3, 0.10.4
  @backstage/frontend-defaults                                     0.1.4, 0.1.5
  @backstage/frontend-plugin-api                                   0.9.3, 0.9.4
  @backstage/frontend-test-utils                                   0.2.4, 0.2.5
  @backstage/integration-aws-node                                  0.1.13, 0.1.15
  @backstage/integration-react                                     1.2.2, 1.2.3
  @backstage/integration                                           1.15.2, 1.16.0, 1.16.1
  @backstage/plugin-api-docs                                       0.12.3
  @backstage/plugin-app-backend                                    0.4.4
  @backstage/plugin-app-node                                       0.1.29
  @backstage/plugin-app                                            0.1.4, 0.1.5
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.4
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.4
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.3.2
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.4
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.4
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.4
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.4
  @backstage/plugin-auth-backend-module-github-provider            0.2.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.4
  @backstage/plugin-auth-backend-module-google-provider            0.2.4
  @backstage/plugin-auth-backend-module-guest-provider             0.2.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.4
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.4
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.4
  @backstage/plugin-auth-backend-module-okta-provider              0.1.4
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.4
  @backstage/plugin-auth-backend                                   0.24.2
  @backstage/plugin-auth-node                                      0.5.4, 0.5.6
  @backstage/plugin-auth-react                                     0.1.11
  @backstage/plugin-bitbucket-cloud-common                         0.2.27
  @backstage/plugin-catalog-backend-module-github                  0.7.9
  @backstage/plugin-catalog-backend-module-gitlab                  0.6.2
  @backstage/plugin-catalog-backend-module-logs                    0.1.6
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.4
  @backstage/plugin-catalog-backend                                1.30.0
  @backstage/plugin-catalog-common                                 1.1.2, 1.1.3
  @backstage/plugin-catalog-graph                                  0.4.15
  @backstage/plugin-catalog-import                                 0.12.9
  @backstage/plugin-catalog-node                                   1.15.1
  @backstage/plugin-catalog-react                                  1.15.0, 1.15.1
  @backstage/plugin-catalog                                        1.26.1
  @backstage/plugin-events-node                                    0.4.7
  @backstage/plugin-kubernetes-backend                             0.19.2
  @backstage/plugin-kubernetes-common                              0.9.2
  @backstage/plugin-kubernetes-node                                0.2.2
  @backstage/plugin-kubernetes-react                               0.5.3
  @backstage/plugin-kubernetes                                     0.12.3
  @backstage/plugin-org                                            0.6.35
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.4
  @backstage/plugin-permission-backend                             0.5.53
  @backstage/plugin-permission-common                              0.8.2, 0.8.3, 0.8.4
  @backstage/plugin-permission-node                                0.8.7
  @backstage/plugin-permission-react                               0.4.29, 0.4.30
  @backstage/plugin-proxy-backend                                  0.5.10
  @backstage/plugin-proxy-node                                     0.1.0
  @backstage/plugin-scaffolder-backend-module-azure                0.2.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.5
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.6
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.5
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.5
  @backstage/plugin-scaffolder-backend-module-github               0.5.5
  @backstage/plugin-scaffolder-backend-module-gitlab               0.7.1
  @backstage/plugin-scaffolder-backend                             1.29.0
  @backstage/plugin-scaffolder-common                              1.5.7, 1.5.8, 1.5.9
  @backstage/plugin-scaffolder-node-test-utils                     0.1.18
  @backstage/plugin-scaffolder-node                                0.5.0, 0.6.3
  @backstage/plugin-scaffolder-react                               1.14.2, 1.14.3
  @backstage/plugin-scaffolder                                     1.27.3, 1.27.4
  @backstage/plugin-search-backend-module-catalog                  0.3.0
  @backstage/plugin-search-backend-module-pg                       0.5.40
  @backstage/plugin-search-backend-module-techdocs                 0.3.5
  @backstage/plugin-search-backend-node                            1.3.7
  @backstage/plugin-search-backend                                 1.8.1
  @backstage/plugin-search-common                                  1.2.16, 1.2.17
  @backstage/plugin-search-react                                   1.8.5
  @backstage/plugin-search                                         1.4.22
  @backstage/plugin-signals-react                                  0.0.9
  @backstage/plugin-techdocs-backend                               1.11.5
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.20
  @backstage/plugin-techdocs-node                                  1.12.16
  @backstage/plugin-techdocs-react                                 1.2.13
  @backstage/plugin-techdocs                                       1.12.1
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.18
  @backstage/release-manifests                                     0.0.12
  @backstage/test-utils                                            1.7.3, 1.7.4
  @backstage/theme                                                 0.5.7, 0.6.3
  @backstage/types                                                 1.2.0, 1.2.1
  @backstage/version-bridge                                        1.0.10

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by MihaiTabara** [comment]
Discussed this in the triaging meeting. I believe this was fixed in yesterday's [1.35.1](https://github.com/backstage/backstage/releases/tag/v1.35.1).

**Comment by Alex-C-github** [comment]
Hi @MihaiTabara ,

I just tested in 1.35.1, the issue is still there.

**Comment by nBerg** [comment]
This error still exists and can be reproduced on the demo site with the template provided in the description
