### ISSUE TITLE
Secret values leaked in logs by the scaffolder fetch template action

### ISSUE THREAD

**Issue by martina-equinix** [backstage/backstage#30876]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
scaffolder template secret leaked logs
```

### 🗃️ Project Area

Software Templates

### 🔗 External Integration

N/A

### 📝 Description & Context

While using secret fields marked as `ui:field: Secret`, I noticed that the secret value was actually printed in the logs when using the `fetch:template` scaffolder action.

You can see in this log sample that the word `querty` (which was supposed to be a secret) is part of the info logs:
```
2025-08-13T11:04:04.605Z scaffolder info info: Running fetch:template in dry-run mode with inputs (secrets redacted): {
  "url": "./skeleton",
  "values": {
    "key": "k1",
    "secret": "***"
  }
} {"span_id":"7467f0f5d64e8fe1","trace_flags":"01","trace_id":"63c3358388cd1a7a53e0cf71b2776cd2"} trace_id="63c3358388cd1a7a53e0cf71b2776cd2" span_id="7467f0f5d64e8fe1" trace_flags="01"
2025-08-13T11:04:04.607Z scaffolder info info: Fetching template content from remote URL {"span_id":"7467f0f5d64e8fe1","trace_flags":"01","trace_id":"63c3358388cd1a7a53e0cf71b2776cd2"} trace_id="63c3358388cd1a7a53e0cf71b2776cd2" span_id="7467f0f5d64e8fe1" trace_flags="01"
2025-08-13T11:04:04.611Z scaffolder info info: Listing files and directories in template {"span_id":"7467f0f5d64e8fe1","trace_flags":"01","trace_id":"63c3358388cd1a7a53e0cf71b2776cd2"} trace_id="63c3358388cd1a7a53e0cf71b2776cd2" span_id="7467f0f5d64e8fe1" trace_flags="01"
2025-08-13T11:04:04.612Z scaffolder info info: Processing 1 template files/directories with input values {"key":"k1","secret":"***","span_id":"7467f0f5d64e8fe1","trace_flags":"01","trace_id":"63c3358388cd1a7a53e0cf71b2776cd2"} key="k1" secret="qwerty" trace_id="63c3358388cd1a7a53e0cf71b2776cd2" span_id="7467f0f5d64e8fe1" trace_flags="01"
2025-08-13T11:04:04.622Z scaffolder info info: Writing file espull.yaml to template output path with mode 33188. {"span_id":"7467f0f5d64e8fe1","trace_flags":"01","trace_id":"63c3358388cd1a7a53e0cf71b2776cd2"} trace_id="63c3358388cd1a7a53e0cf71b2776cd2" span_id="7467f0f5d64e8fe1" trace_flags="01"
2025-08-13T11:04:04.623Z scaffolder info info: Template result written to /var/folders/cp/h3nydp651cv207dz1xvv0czw0000gp/T/dry-run-95b62c07-e5e9-4371-ab3d-8448aca33804 {"span_id":"7467f0f5d64e8fe1","trace_flags":"01","trace_id":"63c3358388cd1a7a53e0cf71b2776cd2"} trace_id="63c3358388cd1a7a53e0cf71b2776cd2" span_id="7467f0f5d64e8fe1" trace_flags="01"
2025-08-13T11:04:04.626Z scaffolder info info: Running dry-run:extract in dry-run mode with inputs (secrets redacted): {} {"span_id":"7467f0f5d64e8fe1","trace_flags":"01","trace_id":"63c3358388cd1a7a53e0cf71b2776cd2"} trace_id="63c3358388cd1a7a53e0cf71b2776cd2" span_id="7467f0f5d64e8fe1" trace_flags="01"
2025-08-13T11:04:04.631Z scaffolder debug scaffolder.task isAuditEvent=true eventId="task" severityLevel="low" actor={"actorId":"user:development/guest","ip":"::1","hostname":"localhost","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"} request={"url":"/api/scaffolder/v2/dry-run","method":"POST"} meta={"actionType":"dry-run","templateRef":"Template:default/secrets-test","parameters":[{"title":"Fill in some steps","required":["key","secret"],"properties":{"key":{"title":"Key","type":"string","pattern":"^[\\w-]+$","description":"The name of the secret"},"secret":{"title":"Secret","type":"string","ui:field":"Secret","description":"Actual secret value"}}}]} status="succeeded" trace_id="63c3358388cd1a7a53e0cf71b2776cd2" span_id="7467f0f5d64e8fe1" trace_flags="01"
2025-08-13T11:04:04.631Z rootHttpRouter info [2025-08-13T11:04:04.631Z] "POST /api/scaffolder/v2/dry-run HTTP/1.1" 200 0 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" type="incomingRequest" date="2025-08-13T11:04:04.631Z" method="POST" url="/api/scaffolder/v2/dry-run" status=200 httpVersion="1.1" userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" referrer="http://localhost:3000/" trace_id="63c3358388cd1a7a53e0cf71b2776cd2" span_id="7467f0f5d64e8fe1" trace_flags="01"
```

### 👍 Expected Behavior

The expected behaviour is that the secret fields stay redacted. You can see that in some logs they are redacted but not on line 10 it appears in plain text.

### 📦 Reproduction Repo

https://github.com/martina-equinix/backstage-issue-secrets

### 🥾 Reproduction steps

Tested in versions `1.39.0` and `1.41.1`:

1. Clone repo
2. Go to Create -> kebab menu -> Manage Templates -> load template
3. Load the folder where you cloned the repo
4. Go through the steps, type a key and a secret value
5. Look at the backstage backend logs and search for the secret that you typed

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Undecided

**Comment by benjdlambert** [comment]
Thanks for reporting this! We've got a fix and a patch release on the way!

**Comment by benjdlambert** [comment]
For transparency, we published 1.41.2 and published a security advisory for the `scaffolder-backend` package https://github.com/backstage/backstage/security/advisories/GHSA-3x3q-ghcp-whf7

Thanks @martina-equinix! 🙏

**Comment by abhisheksharma-sp** [comment]
This is still not fixed. If you have complex, sensitive info
Current backstage:
```

version": "1.41.2
packages/backend/package.json:    "@backstage/plugin-scaffolder-backend": "^2.1.1",
```

With simple secrets: like hello@123
```
"devVaultSecretKeys":"***",
```

With a complex example:  {"DEV_API_KEY": "secret1", "DEV_DB_PASS": "secret2"}
```
devVaultSecretKeys":"{\"DEV_API_KEY\": \"secret1\", \"DEV_DB_PASS\": \"secret2\"}"
```

**Comment by benjdlambert** [comment]
Hmm I actually think that this might be something separate. I don't think we support complex keys in secrets at the moment. And I think with the latest release that went out yesterday this might be now enforced with the OpenAPI schema. 

https://github.com/backstage/backstage/pull/27771/files#diff-86bd035d3e543dde140c8b6f2456a201418b231d8d4e5b380e96a6541ed31ed1R28

I'm happy to create a ticket to add support for complex secret types though :pray:

**Comment by abhisheksharma-sp** [comment]
> Hmm I actually think that this might be something separate. I don't think we support complex keys in secrets at the moment. And I think with the latest release that went out yesterday this might be now enforced with the OpenAPI schema.
> 
> https://github.com/backstage/backstage/pull/27771/files#diff-86bd035d3e543dde140c8b6f2456a201418b231d8d4e5b380e96a6541ed31ed1R28
> 
> I'm happy to create a ticket to add support for complex secret types though 🙏

Interesting — the secret feature itself works fine with complex data and I’m able to use it correctly. The only issue I see is in the template output, so I’m a bit confused when you say it’s not supported.
